"""empty message

Revision ID: b53f2c9a6407
Revises: dfc441ca5ba7
Create Date: 2024-05-10 15:15:17.114552

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils
import sqlmodel # added


# revision identifiers, used by Alembic.
revision = 'b53f2c9a6407'
down_revision = 'dfc441ca5ba7'
branch_labels = None
depends_on = None


def upgrade():
    op.execute("CREATE EXTENSION IF NOT EXISTS pg_trgm") 
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('ExamPaper', 'exam_duration',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint('ExamPaper_description_key', 'ExamPaper', type_='unique')
    op.drop_constraint('ExamPaper_name_key', 'ExamPaper', type_='unique')
    op.drop_constraint('ExamPaper_year_of_exam_key', 'ExamPaper', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('ExamPaper_year_of_exam_key', 'ExamPaper', ['year_of_exam'])
    op.create_unique_constraint('ExamPaper_name_key', 'ExamPaper', ['name'])
    op.create_unique_constraint('ExamPaper_description_key', 'ExamPaper', ['description'])
    op.alter_column('ExamPaper', 'exam_duration',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
