"""empty message

Revision ID: 01ec4c744661
Revises: 68bbc189a1dd
Create Date: 2024-05-14 21:04:12.553247

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils
import sqlmodel # added


# revision identifiers, used by Alembic.
revision = '01ec4c744661'
down_revision = '68bbc189a1dd'
branch_labels = None
depends_on = None


def upgrade():
    op.execute("CREATE EXTENSION IF NOT EXISTS pg_trgm") 
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('AnswerAssociationLink',
    sa.Column('id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('parent_id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('child_id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.ForeignKeyConstraint(['child_id'], ['Answer.id'], ),
    sa.ForeignKeyConstraint(['parent_id'], ['Answer.id'], ),
    sa.PrimaryKeyConstraint('id', 'parent_id', 'child_id')
    )
    op.create_index(op.f('ix_AnswerAssociationLink_id'), 'AnswerAssociationLink', ['id'], unique=False)
    op.drop_constraint('Answer_parent_id_fkey', 'Answer', type_='foreignkey')
    op.drop_column('Answer', 'parent_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Answer', sa.Column('parent_id', sa.UUID(), autoincrement=False, nullable=True))
    op.create_foreign_key('Answer_parent_id_fkey', 'Answer', 'Answer', ['parent_id'], ['id'])
    op.drop_index(op.f('ix_AnswerAssociationLink_id'), table_name='AnswerAssociationLink')
    op.drop_table('AnswerAssociationLink')
    # ### end Alembic commands ###
