"""empty message

Revision ID: cdd36af69e58
Revises: 21f5d7fd47b9
Create Date: 2024-05-12 10:03:07.812265

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils
import sqlmodel # added


# revision identifiers, used by Alembic.
revision = 'cdd36af69e58'
down_revision = '21f5d7fd47b9'
branch_labels = None
depends_on = None


def upgrade():
    op.execute("CREATE EXTENSION IF NOT EXISTS pg_trgm") 
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('MainQuestion',
    sa.Column('text', sa.TEXT(), nullable=False),
    sa.Column('marks', sa.Integer(), nullable=True),
    sa.Column('id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('slug', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('question_set_id', sqlmodel.sql.sqltypes.GUID(), nullable=True),
    sa.Column('created_by_id', sqlmodel.sql.sqltypes.GUID(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['User.id'], ),
    sa.ForeignKeyConstraint(['question_set_id'], ['QuestionSet.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_MainQuestion_id'), 'MainQuestion', ['id'], unique=False)
    op.create_foreign_key(None, 'SubQuestion', 'MainQuestion', ['main_question_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'SubQuestion', type_='foreignkey')
    op.drop_index(op.f('ix_MainQuestion_id'), table_name='MainQuestion')
    op.drop_table('MainQuestion')
    # ### end Alembic commands ###
