"""empty message

Revision ID: fc8135013d9b
Revises: 130272ec739a
Create Date: 2024-05-10 15:01:33.962805

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils
import sqlmodel # added


# revision identifiers, used by Alembic.
revision = 'fc8135013d9b'
down_revision = '130272ec739a'
branch_labels = None
depends_on = None


def upgrade():
    op.execute("CREATE EXTENSION IF NOT EXISTS pg_trgm") 
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ExamInstruction',
    sa.Column('id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('instruction_text', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('slug', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_by_id', sqlmodel.sql.sqltypes.GUID(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['User.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('instruction_text'),
    sa.UniqueConstraint('slug')
    )
    op.create_index(op.f('ix_ExamInstruction_id'), 'ExamInstruction', ['id'], unique=False)
    op.create_foreign_key(None, 'InstructionExamsLink', 'ExamInstruction', ['instruction_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'InstructionExamsLink', type_='foreignkey')
    op.drop_index(op.f('ix_ExamInstruction_id'), table_name='ExamInstruction')
    op.drop_table('ExamInstruction')
    # ### end Alembic commands ###
