"""empty message

Revision ID: c5851dbcd1eb
Revises: be9cc733faad
Create Date: 2024-05-12 08:09:18.666161

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils
import sqlmodel # added


# revision identifiers, used by Alembic.
revision = 'c5851dbcd1eb'
down_revision = 'be9cc733faad'
branch_labels = None
depends_on = None


def upgrade():
    op.execute("CREATE EXTENSION IF NOT EXISTS pg_trgm") 
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('QuestionSet',
    sa.Column('id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('title', sa.Enum('QUESTION_ONE', 'QUESTION_TWO', 'QUESTION_THREE', 'QUESTION_FOUR', 'QUESTION_FIVE', 'QUESTION_SIX', 'QUESTION_SEVEN', 'QUESTION_EIGHT', 'QUESTION_NINE', 'QUESTION_TEN', name='questionsettitleenum'), nullable=True),
    sa.Column('slug', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_by_id', sqlmodel.sql.sqltypes.GUID(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['User.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_index(op.f('ix_QuestionSet_id'), 'QuestionSet', ['id'], unique=False)
    op.create_table('MainQuestion',
    sa.Column('text', sa.TEXT(), nullable=False),
    sa.Column('marks', sa.Integer(), nullable=True),
    sa.Column('id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('slug', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('question_set_id', sqlmodel.sql.sqltypes.GUID(), nullable=True),
    sa.Column('created_by_id', sqlmodel.sql.sqltypes.GUID(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['User.id'], ),
    sa.ForeignKeyConstraint(['question_set_id'], ['QuestionSet.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_index(op.f('ix_MainQuestion_id'), 'MainQuestion', ['id'], unique=False)
    op.create_table('SubQuestion',
    sa.Column('id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('text', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('marks', sa.Integer(), nullable=True),
    sa.Column('main_question_id', sqlmodel.sql.sqltypes.GUID(), nullable=True),
    sa.Column('created_by_id', sqlmodel.sql.sqltypes.GUID(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['User.id'], ),
    sa.ForeignKeyConstraint(['main_question_id'], ['MainQuestion.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_SubQuestion_id'), 'SubQuestion', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_SubQuestion_id'), table_name='SubQuestion')
    op.drop_table('SubQuestion')
    op.drop_index(op.f('ix_MainQuestion_id'), table_name='MainQuestion')
    op.drop_table('MainQuestion')
    op.drop_index(op.f('ix_QuestionSet_id'), table_name='QuestionSet')
    op.drop_table('QuestionSet')
    # ### end Alembic commands ###
