"""empty message

Revision ID: 30513f3e269b
Revises: 9b958fa398d2
Create Date: 2024-05-09 13:12:16.691383

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils
import sqlmodel # added


# revision identifiers, used by Alembic.
revision = '30513f3e269b'
down_revision = '9b958fa398d2'
branch_labels = None
depends_on = None


def upgrade():
    op.execute("CREATE EXTENSION IF NOT EXISTS pg_trgm") 
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ExamInstruction',
    sa.Column('id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('instruction_text', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_by_id', sqlmodel.sql.sqltypes.GUID(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['User.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('instruction_text')
    )
    op.create_index(op.f('ix_ExamInstruction_id'), 'ExamInstruction', ['id'], unique=False)
    op.create_table('ExamPaper',
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('year_of_exam', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('exam_duration', sa.Integer(), nullable=False),
    sa.Column('exam_date', sa.DateTime(), nullable=True),
    sa.Column('id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('tags', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('slug', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_by_id', sqlmodel.sql.sqltypes.GUID(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['User.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('description'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('slug'),
    sa.UniqueConstraint('year_of_exam')
    )
    op.create_index(op.f('ix_ExamPaper_id'), 'ExamPaper', ['id'], unique=False)
    op.create_table('InstructionExamsLink',
    sa.Column('id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('instruction_id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('exam_id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.ForeignKeyConstraint(['exam_id'], ['ExamPaper.id'], ),
    sa.ForeignKeyConstraint(['instruction_id'], ['ExamInstruction.id'], ),
    sa.PrimaryKeyConstraint('id', 'instruction_id', 'exam_id')
    )
    op.create_index(op.f('ix_InstructionExamsLink_id'), 'InstructionExamsLink', ['id'], unique=False)
    op.create_table('ModuleExamsLink',
    sa.Column('id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('module_id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('exam_id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.ForeignKeyConstraint(['exam_id'], ['ExamPaper.id'], ),
    sa.ForeignKeyConstraint(['module_id'], ['Module.id'], ),
    sa.PrimaryKeyConstraint('id', 'module_id', 'exam_id')
    )
    op.create_index(op.f('ix_ModuleExamsLink_id'), 'ModuleExamsLink', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ModuleExamsLink_id'), table_name='ModuleExamsLink')
    op.drop_table('ModuleExamsLink')
    op.drop_index(op.f('ix_InstructionExamsLink_id'), table_name='InstructionExamsLink')
    op.drop_table('InstructionExamsLink')
    op.drop_index(op.f('ix_ExamPaper_id'), table_name='ExamPaper')
    op.drop_table('ExamPaper')
    op.drop_index(op.f('ix_ExamInstruction_id'), table_name='ExamInstruction')
    op.drop_table('ExamInstruction')
    # ### end Alembic commands ###
