"""empty message

Revision ID: 6fde338b5955
Revises: fdddc371e454
Create Date: 2024-05-08 09:54:21.952503

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils
import sqlmodel # added


# revision identifiers, used by Alembic.
revision = '6fde338b5955'
down_revision = 'fdddc371e454'
branch_labels = None
depends_on = None


def upgrade():
    op.execute("CREATE EXTENSION IF NOT EXISTS pg_trgm") 
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Programme',
    sa.Column('name', sa.Enum('CERTIFICATE', 'DIPLOMA', 'UNDERGRADUATE', 'MASTERS', 'POSTGRADUATE_DIPLOMA', 'PHD_PROGRAMMES', 'ONLINE_MBA', 'OTHERS', name='programmetypes'), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('slug', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_by_id', sqlmodel.sql.sqltypes.GUID(), nullable=True),
    sa.Column('image_id', sqlmodel.sql.sqltypes.GUID(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['User.id'], ),
    sa.ForeignKeyConstraint(['image_id'], ['ImageMedia.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('slug')
    )
    op.create_index(op.f('ix_Programme_id'), 'Programme', ['id'], unique=False)
    op.create_foreign_key(None, 'Course', 'Programme', ['programme_id'], ['id'])
    op.create_foreign_key(None, 'ProgrammeDepartmentLink', 'Programme', ['programme_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'ProgrammeDepartmentLink', type_='foreignkey')
    op.drop_constraint(None, 'Course', type_='foreignkey')
    op.drop_index(op.f('ix_Programme_id'), table_name='Programme')
    op.drop_table('Programme')
    # ### end Alembic commands ###
