"""empty message

Revision ID: 5668b98b64ae
Revises: e0fa8f8ca560
Create Date: 2024-05-08 10:31:02.178738

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils
import sqlmodel # added


# revision identifiers, used by Alembic.
revision = '5668b98b64ae'
down_revision = 'e0fa8f8ca560'
branch_labels = None
depends_on = None


def upgrade():
    op.execute("CREATE EXTENSION IF NOT EXISTS pg_trgm") 
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Campus', sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('Campus', sa.Column('address', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.drop_column('Campus', 'location')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Campus', sa.Column('location', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('Campus', 'address')
    op.drop_column('Campus', 'description')
    # ### end Alembic commands ###
