"""empty message

Revision ID: d315108f2a02
Revises: d4d32aab32c2
Create Date: 2024-05-10 19:41:45.330321

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils
import sqlmodel # added


# revision identifiers, used by Alembic.
revision = 'd315108f2a02'
down_revision = 'd4d32aab32c2'
branch_labels = None
depends_on = None


def upgrade():
    op.execute("CREATE EXTENSION IF NOT EXISTS pg_trgm") 
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ExamInstruction',
    sa.Column('id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('slug', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_by_id', sqlmodel.sql.sqltypes.GUID(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['User.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('slug')
    )
    op.create_index(op.f('ix_ExamInstruction_id'), 'ExamInstruction', ['id'], unique=False)
    op.create_foreign_key(None, 'InstructionExamsLink', 'ExamInstruction', ['instruction_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'InstructionExamsLink', type_='foreignkey')
    op.drop_index(op.f('ix_ExamInstruction_id'), table_name='ExamInstruction')
    op.drop_table('ExamInstruction')
    # ### end Alembic commands ###
