"""empty message

Revision ID: cda3c0691120
Revises: 081c3c2c928b
Create Date: 2024-05-12 09:46:49.383414

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils
import sqlmodel # added


# revision identifiers, used by Alembic.
revision = 'cda3c0691120'
down_revision = '081c3c2c928b'
branch_labels = None
depends_on = None


def upgrade():
    op.execute("CREATE EXTENSION IF NOT EXISTS pg_trgm") 
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('MainQuestion_slug_key', 'MainQuestion', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('MainQuestion_slug_key', 'MainQuestion', ['slug'])
    # ### end Alembic commands ###
