"""empty message

Revision ID: 6bf09b68a03b
Revises: e53c459fd5cc
Create Date: 2024-05-11 20:22:29.902673

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils
import sqlmodel # added


# revision identifiers, used by Alembic.
revision = '6bf09b68a03b'
down_revision = 'e53c459fd5cc'
branch_labels = None
depends_on = None


def upgrade():
    op.execute("CREATE EXTENSION IF NOT EXISTS pg_trgm") 
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('ExamPaper_hash_code_key', 'ExamPaper', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('ExamPaper_hash_code_key', 'ExamPaper', ['hash_code'])
    # ### end Alembic commands ###
