"""empty message

Revision ID: a94e4234ecec
Revises: 01ec4c744661
Create Date: 2024-05-14 21:09:36.024062

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils
import sqlmodel # added


# revision identifiers, used by Alembic.
revision = 'a94e4234ecec'
down_revision = '01ec4c744661'
branch_labels = None
depends_on = None


def upgrade():
    op.execute("CREATE EXTENSION IF NOT EXISTS pg_trgm") 
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Answer',
    sa.Column('text', sa.TEXT(), nullable=False),
    sa.Column('id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('likes', sa.Integer(), nullable=False),
    sa.Column('dislikes', sa.Integer(), nullable=False),
    sa.Column('reviewed', sa.Boolean(), nullable=False),
    sa.Column('auto_answer', sa.Boolean(), nullable=False),
    sa.Column('created_by_id', sqlmodel.sql.sqltypes.GUID(), nullable=True),
    sa.Column('parent_id', sqlmodel.sql.sqltypes.GUID(), nullable=True),
    sa.Column('main_question_id', sqlmodel.sql.sqltypes.GUID(), nullable=True),
    sa.Column('sub_question_id', sqlmodel.sql.sqltypes.GUID(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['User.id'], ),
    sa.ForeignKeyConstraint(['main_question_id'], ['MainQuestion.id'], ),
    sa.ForeignKeyConstraint(['parent_id'], ['Answer.id'], ),
    sa.ForeignKeyConstraint(['sub_question_id'], ['SubQuestion.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_Answer_id'), 'Answer', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_Answer_id'), table_name='Answer')
    op.drop_table('Answer')
    # ### end Alembic commands ###
