"""empty message

Revision ID: 1214e000b25f
Revises: cd18fabb743f
Create Date: 2024-05-11 19:56:42.370467

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils
import sqlmodel # added


# revision identifiers, used by Alembic.
revision = '1214e000b25f'
down_revision = 'cd18fabb743f'
branch_labels = None
depends_on = None


def upgrade():
    op.execute("CREATE EXTENSION IF NOT EXISTS pg_trgm") 
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ExamPaper', sa.Column('hash_code', sa.String(length=64), nullable=False))
    op.drop_constraint('ExamPaper_hash_value_key', 'ExamPaper', type_='unique')
    op.create_unique_constraint(None, 'ExamPaper', ['hash_code'])
    op.drop_column('ExamPaper', 'hash_value')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ExamPaper', sa.Column('hash_value', sa.VARCHAR(length=64), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'ExamPaper', type_='unique')
    op.create_unique_constraint('ExamPaper_hash_value_key', 'ExamPaper', ['hash_value'])
    op.drop_column('ExamPaper', 'hash_code')
    # ### end Alembic commands ###
