"""empty message

Revision ID: 60abe9266b48
Revises: c515f9deb3d5
Create Date: 2024-05-10 20:40:55.574395

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils
import sqlmodel # added


# revision identifiers, used by Alembic.
revision = '60abe9266b48'
down_revision = 'c515f9deb3d5'
branch_labels = None
depends_on = None


def upgrade():
    op.execute("CREATE EXTENSION IF NOT EXISTS pg_trgm") 
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ExamPaper',
    sa.Column('year_of_exam', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('exam_duration', sa.Integer(), nullable=True),
    sa.Column('exam_date', sa.Date(), nullable=True),
    sa.Column('id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('created_by_id', sqlmodel.sql.sqltypes.GUID(), nullable=True),
    sa.Column('description_id', sqlmodel.sql.sqltypes.GUID(), nullable=True),
    sa.Column('title_id', sqlmodel.sql.sqltypes.GUID(), nullable=True),
    sa.Column('institution_id', sqlmodel.sql.sqltypes.GUID(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['User.id'], ),
    sa.ForeignKeyConstraint(['description_id'], ['ExamDescription.id'], ),
    sa.ForeignKeyConstraint(['institution_id'], ['Institution.id'], ),
    sa.ForeignKeyConstraint(['title_id'], ['ExamTitle.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ExamPaper_id'), 'ExamPaper', ['id'], unique=False)
    op.create_foreign_key(None, 'InstructionExamsLink', 'ExamPaper', ['exam_id'], ['id'])
    op.create_foreign_key(None, 'ModuleExamsLink', 'ExamPaper', ['exam_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'ModuleExamsLink', type_='foreignkey')
    op.drop_constraint(None, 'InstructionExamsLink', type_='foreignkey')
    op.drop_index(op.f('ix_ExamPaper_id'), table_name='ExamPaper')
    op.drop_table('ExamPaper')
    # ### end Alembic commands ###
