"""empty message

Revision ID: a360f8beb46a
Revises: fc8135013d9b
Create Date: 2024-05-10 15:06:13.134305

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils
import sqlmodel # added


# revision identifiers, used by Alembic.
revision = 'a360f8beb46a'
down_revision = 'fc8135013d9b'
branch_labels = None
depends_on = None


def upgrade():
    op.execute("CREATE EXTENSION IF NOT EXISTS pg_trgm") 
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('ExamInstruction_slug_key', 'ExamInstruction', type_='unique')
    op.drop_column('ExamInstruction', 'slug')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ExamInstruction', sa.Column('slug', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.create_unique_constraint('ExamInstruction_slug_key', 'ExamInstruction', ['slug'])
    # ### end Alembic commands ###
