"""empty message

Revision ID: 038ee86c4365
Revises: ee0243950f69
Create Date: 2024-05-06 16:03:45.478540

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils
import sqlmodel # added


# revision identifiers, used by Alembic.
revision = '038ee86c4365'
down_revision = 'ee0243950f69'
branch_labels = None
depends_on = None


def upgrade():
    op.execute("CREATE EXTENSION IF NOT EXISTS pg_trgm") 
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Faculty', sa.Column('image_id', sqlmodel.sql.sqltypes.GUID(), nullable=True))
    op.create_foreign_key(None, 'Faculty', 'ImageMedia', ['image_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'Faculty', type_='foreignkey')
    op.drop_column('Faculty', 'image_id')
    # ### end Alembic commands ###
