"""empty message

Revision ID: fdddc371e454
Revises: fe882f4d5d37
Create Date: 2024-05-08 09:48:04.757026

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils
import sqlmodel # added
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'fdddc371e454'
down_revision = 'fe882f4d5d37'
branch_labels = None
depends_on = None


def upgrade():
    op.execute("CREATE EXTENSION IF NOT EXISTS pg_trgm") 
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Programme', 'name',
               existing_type=postgresql.ENUM('Certificate', 'Diploma', 'Undergraduate', 'Masters', 'Postgraduates Diploma', 'PhD Programmes', 'Online MBA', 'Others', name='programme_type'),
               type_=sa.Enum('CERTIFICATE', 'DIPLOMA', 'UNDERGRADUATE', 'MASTERS', 'POSTGRADUATE_DIPLOMA', 'PHD_PROGRAMMES', 'ONLINE_MBA', 'OTHERS', name='programmetypes'),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Programme', 'name',
               existing_type=sa.Enum('CERTIFICATE', 'DIPLOMA', 'UNDERGRADUATE', 'MASTERS', 'POSTGRADUATE_DIPLOMA', 'PHD_PROGRAMMES', 'ONLINE_MBA', 'OTHERS', name='programmetypes'),
               type_=postgresql.ENUM('Certificate', 'Diploma', 'Undergraduate', 'Masters', 'Postgraduates Diploma', 'PhD Programmes', 'Online MBA', 'Others', name='programme_type'),
               existing_nullable=False)
    # ### end Alembic commands ###
