"""empty message

Revision ID: acabc4706f4d
Revises: 5a883b0a5fdd
Create Date: 2024-05-12 21:46:43.467501

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils
import sqlmodel # added


# revision identifiers, used by Alembic.
revision = 'acabc4706f4d'
down_revision = '5a883b0a5fdd'
branch_labels = None
depends_on = None


def upgrade():
    op.execute("CREATE EXTENSION IF NOT EXISTS pg_trgm") 
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('MainQuestion', sa.Column('exam_paper_id', sqlmodel.sql.sqltypes.GUID(), nullable=True))
    op.alter_column('MainQuestion', 'order_within_question_set',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_constraint('MainQuestion_order_within_question_set_key', 'MainQuestion', type_='unique')
    op.create_unique_constraint('_questions_order_per_question_set_uc', 'MainQuestion', ['exam_paper_id', 'order_within_question_set', 'question_set_id'])
    op.create_foreign_key(None, 'MainQuestion', 'ExamPaper', ['exam_paper_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'MainQuestion', type_='foreignkey')
    op.drop_constraint('_questions_order_per_question_set_uc', 'MainQuestion', type_='unique')
    op.create_unique_constraint('MainQuestion_order_within_question_set_key', 'MainQuestion', ['order_within_question_set'])
    op.alter_column('MainQuestion', 'order_within_question_set',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('MainQuestion', 'exam_paper_id')
    # ### end Alembic commands ###
