"""empty message

Revision ID: dfecbbfae057
Revises: a5bb11498728
Create Date: 2024-05-08 10:22:44.079355

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils
import sqlmodel # added


# revision identifiers, used by Alembic.
revision = 'dfecbbfae057'
down_revision = 'a5bb11498728'
branch_labels = None
depends_on = None


def upgrade():
    op.execute("CREATE EXTENSION IF NOT EXISTS pg_trgm") 
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('ProgrammeDepartmentLink_department_id_key', 'ProgrammeDepartmentLink', type_='unique')
    op.drop_constraint('ProgrammeDepartmentLink_programme_id_key', 'ProgrammeDepartmentLink', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('ProgrammeDepartmentLink_programme_id_key', 'ProgrammeDepartmentLink', ['programme_id'])
    op.create_unique_constraint('ProgrammeDepartmentLink_department_id_key', 'ProgrammeDepartmentLink', ['department_id'])
    # ### end Alembic commands ###
