"""empty message

Revision ID: dfc441ca5ba7
Revises: a360f8beb46a
Create Date: 2024-05-10 15:07:22.021334

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils
import sqlmodel # added


# revision identifiers, used by Alembic.
revision = 'dfc441ca5ba7'
down_revision = 'a360f8beb46a'
branch_labels = None
depends_on = None


def upgrade():
    op.execute("CREATE EXTENSION IF NOT EXISTS pg_trgm") 
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ExamInstruction', sa.Column('slug', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.create_unique_constraint(None, 'ExamInstruction', ['slug'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'ExamInstruction', type_='unique')
    op.drop_column('ExamInstruction', 'slug')
    # ### end Alembic commands ###
