"""empty message

Revision ID: 364d6e71378f
Revises: c5851dbcd1eb
Create Date: 2024-05-12 08:33:35.634162

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils
import sqlmodel # added


# revision identifiers, used by Alembic.
revision = '364d6e71378f'
down_revision = 'c5851dbcd1eb'
branch_labels = None
depends_on = None


def upgrade():
    op.execute("CREATE EXTENSION IF NOT EXISTS pg_trgm") 
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ExamPaperQuestionLink',
    sa.Column('id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('question_set_id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('exam_id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.ForeignKeyConstraint(['exam_id'], ['ExamPaper.id'], ),
    sa.ForeignKeyConstraint(['question_set_id'], ['QuestionSet.id'], ),
    sa.PrimaryKeyConstraint('id', 'question_set_id', 'exam_id')
    )
    op.create_index(op.f('ix_ExamPaperQuestionLink_id'), 'ExamPaperQuestionLink', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ExamPaperQuestionLink_id'), table_name='ExamPaperQuestionLink')
    op.drop_table('ExamPaperQuestionLink')
    # ### end Alembic commands ###
