"""empty message

Revision ID: eec2d174ae4a
Revises: d460e19ea7bc
Create Date: 2024-05-07 21:42:30.391403

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils
import sqlmodel # added


# revision identifiers, used by Alembic.
revision = 'eec2d174ae4a'
down_revision = 'd460e19ea7bc'
branch_labels = None
depends_on = None


def upgrade():
    op.execute("CREATE EXTENSION IF NOT EXISTS pg_trgm") 
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Programme',
    sa.Column('name', sa.Enum('Certificate', 'Diploma', 'Undergraduate', 'Masters', 'Postgraduates Diploma', 'PhD Programmes', 'Online MBA', 'Others', name='programme_type'), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('slug', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_by_id', sqlmodel.sql.sqltypes.GUID(), nullable=True),
    sa.Column('image_id', sqlmodel.sql.sqltypes.GUID(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['User.id'], ),
    sa.ForeignKeyConstraint(['image_id'], ['ImageMedia.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('slug')
    )
    op.create_index(op.f('ix_Programme_id'), 'Programme', ['id'], unique=False)
    op.create_table('ProgrammeDepartmentLink',
    sa.Column('id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('programme_id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('department_id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.ForeignKeyConstraint(['department_id'], ['Department.id'], ),
    sa.ForeignKeyConstraint(['programme_id'], ['Programme.id'], ),
    sa.PrimaryKeyConstraint('id', 'programme_id', 'department_id'),
    sa.UniqueConstraint('department_id'),
    sa.UniqueConstraint('programme_id')
    )
    op.create_index(op.f('ix_ProgrammeDepartmentLink_id'), 'ProgrammeDepartmentLink', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ProgrammeDepartmentLink_id'), table_name='ProgrammeDepartmentLink')
    op.drop_table('ProgrammeDepartmentLink')
    op.drop_index(op.f('ix_Programme_id'), table_name='Programme')
    op.drop_table('Programme')
    # ### end Alembic commands ###
