"""empty message

Revision ID: 1d43d9bb4e14
Revises: 60175a5892dc
Create Date: 2024-05-07 07:04:24.454177

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils
import sqlmodel # added


# revision identifiers, used by Alembic.
revision = '1d43d9bb4e14'
down_revision = '60175a5892dc'
branch_labels = None
depends_on = None


def upgrade():
    op.execute("CREATE EXTENSION IF NOT EXISTS pg_trgm") 
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Faculty', 'institution_count')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Faculty', sa.Column('institution_count', sa.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
