"""empty message

Revision ID: e80e963c85c1
Revises: c1cecdff31e0
Create Date: 2024-05-11 21:10:22.391639

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils
import sqlmodel # added


# revision identifiers, used by Alembic.
revision = 'e80e963c85c1'
down_revision = 'c1cecdff31e0'
branch_labels = None
depends_on = None


def upgrade():
    op.execute("CREATE EXTENSION IF NOT EXISTS pg_trgm") 
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('ExamPaper', 'hash_code',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.create_unique_constraint(None, 'ExamPaper', ['hash_code'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'ExamPaper', type_='unique')
    op.alter_column('ExamPaper', 'hash_code',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
