"""empty message

Revision ID: a46d1d73e1d0
Revises: 5cadf6dd2084
Create Date: 2024-05-08 20:57:18.419442

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils
import sqlmodel # added


# revision identifiers, used by Alembic.
revision = 'a46d1d73e1d0'
down_revision = '5cadf6dd2084'
branch_labels = None
depends_on = None


def upgrade():
    op.execute("CREATE EXTENSION IF NOT EXISTS pg_trgm") 
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Module', sa.Column('unit_code', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.create_unique_constraint(None, 'Module', ['unit_code'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'Module', type_='unique')
    op.drop_column('Module', 'unit_code')
    # ### end Alembic commands ###
