"""empty message

Revision ID: 2d9db9ae9767
Revises: b70829b9a1ec
Create Date: 2024-05-08 11:31:45.846608

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils
import sqlmodel # added


# revision identifiers, used by Alembic.
revision = '2d9db9ae9767'
down_revision = 'b70829b9a1ec'
branch_labels = None
depends_on = None


def upgrade():
    op.execute("CREATE EXTENSION IF NOT EXISTS pg_trgm") 
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Course', 'programme_id',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Course', 'programme_id',
               existing_type=sa.UUID(),
               nullable=False)
    # ### end Alembic commands ###
