"""empty message

Revision ID: d7d84ba3398f
Revises: fbeed6a355b1
Create Date: 2024-05-11 20:34:41.548524

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils
import sqlmodel # added


# revision identifiers, used by Alembic.
revision = 'd7d84ba3398f'
down_revision = 'fbeed6a355b1'
branch_labels = None
depends_on = None


def upgrade():
    op.execute("CREATE EXTENSION IF NOT EXISTS pg_trgm") 
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ExamPaper',
    sa.Column('year_of_exam', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('exam_duration', sa.Integer(), nullable=True),
    sa.Column('exam_date', sa.Date(), nullable=True),
    sa.Column('id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('created_by_id', sqlmodel.sql.sqltypes.GUID(), nullable=True),
    sa.Column('description_id', sqlmodel.sql.sqltypes.GUID(), nullable=True),
    sa.Column('title_id', sqlmodel.sql.sqltypes.GUID(), nullable=True),
    sa.Column('institution_id', sqlmodel.sql.sqltypes.GUID(), nullable=True),
    sa.Column('hash_code', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['User.id'], ),
    sa.ForeignKeyConstraint(['description_id'], ['ExamDescription.id'], ),
    sa.ForeignKeyConstraint(['institution_id'], ['Institution.id'], ),
    sa.ForeignKeyConstraint(['title_id'], ['ExamTitle.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ExamPaper_id'), 'ExamPaper', ['id'], unique=False)
    op.create_table('InstructionExamsLink',
    sa.Column('id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('instruction_id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('exam_id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.ForeignKeyConstraint(['exam_id'], ['ExamPaper.id'], ),
    sa.ForeignKeyConstraint(['instruction_id'], ['ExamInstruction.id'], ),
    sa.PrimaryKeyConstraint('id', 'instruction_id', 'exam_id')
    )
    op.create_index(op.f('ix_InstructionExamsLink_id'), 'InstructionExamsLink', ['id'], unique=False)
    op.create_table('ModuleExamsLink',
    sa.Column('id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('module_id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('exam_id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.ForeignKeyConstraint(['exam_id'], ['ExamPaper.id'], ),
    sa.ForeignKeyConstraint(['module_id'], ['Module.id'], ),
    sa.PrimaryKeyConstraint('id', 'module_id', 'exam_id')
    )
    op.create_index(op.f('ix_ModuleExamsLink_id'), 'ModuleExamsLink', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ModuleExamsLink_id'), table_name='ModuleExamsLink')
    op.drop_table('ModuleExamsLink')
    op.drop_index(op.f('ix_InstructionExamsLink_id'), table_name='InstructionExamsLink')
    op.drop_table('InstructionExamsLink')
    op.drop_index(op.f('ix_ExamPaper_id'), table_name='ExamPaper')
    op.drop_table('ExamPaper')
    # ### end Alembic commands ###
