"""empty message

Revision ID: e0fa8f8ca560
Revises: d8fdca5a2e83
Create Date: 2024-05-08 10:25:10.907479

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils
import sqlmodel # added


# revision identifiers, used by Alembic.
revision = 'e0fa8f8ca560'
down_revision = 'd8fdca5a2e83'
branch_labels = None
depends_on = None


def upgrade():
    op.execute("CREATE EXTENSION IF NOT EXISTS pg_trgm") 
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('InstitutionFacultyLink_faculty_id_key', 'InstitutionFacultyLink', type_='unique')
    op.drop_constraint('InstitutionFacultyLink_institution_id_key', 'InstitutionFacultyLink', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('InstitutionFacultyLink_institution_id_key', 'InstitutionFacultyLink', ['institution_id'])
    op.create_unique_constraint('InstitutionFacultyLink_faculty_id_key', 'InstitutionFacultyLink', ['faculty_id'])
    # ### end Alembic commands ###
