"""empty message

Revision ID: e5a8910e971c
Revises: 913bd0ffb50b
Create Date: 2024-05-11 22:05:44.708181

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils
import sqlmodel # added


# revision identifiers, used by Alembic.
revision = 'e5a8910e971c'
down_revision = '913bd0ffb50b'
branch_labels = None
depends_on = None


def upgrade():
    op.execute("CREATE EXTENSION IF NOT EXISTS pg_trgm") 
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ExamPaper', sa.Column('course_id', sqlmodel.sql.sqltypes.GUID(), nullable=True))
    op.create_foreign_key(None, 'ExamPaper', 'Course', ['course_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'ExamPaper', type_='foreignkey')
    op.drop_column('ExamPaper', 'course_id')
    # ### end Alembic commands ###
