"""empty message

Revision ID: ff483db59fe9
Revises: 7cf1a431e8b1
Create Date: 2024-05-12 12:09:16.202169

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils
import sqlmodel # added


# revision identifiers, used by Alembic.
revision = 'ff483db59fe9'
down_revision = '7cf1a431e8b1'
branch_labels = None
depends_on = None


def upgrade():
    op.execute("CREATE EXTENSION IF NOT EXISTS pg_trgm") 
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('MainQuestion', sa.Column('order_within_question_set', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('MainQuestion', 'order_within_question_set')
    # ### end Alembic commands ###
