"""empty message

Revision ID: 24bd3c938491
Revises: abd77fa99dc9
Create Date: 2024-05-12 12:33:46.737471

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils
import sqlmodel # added


# revision identifiers, used by Alembic.
revision = '24bd3c938491'
down_revision = 'abd77fa99dc9'
branch_labels = None
depends_on = None


def upgrade():
    op.execute("CREATE EXTENSION IF NOT EXISTS pg_trgm") 
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('MainQuestion_order_within_question_set_key', 'MainQuestion', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('MainQuestion_order_within_question_set_key', 'MainQuestion', ['order_within_question_set'])
    # ### end Alembic commands ###
