"""empty message

Revision ID: fbeed6a355b1
Revises: 6bf09b68a03b
Create Date: 2024-05-11 20:25:44.494623

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils
import sqlmodel # added


# revision identifiers, used by Alembic.
revision = 'fbeed6a355b1'
down_revision = '6bf09b68a03b'
branch_labels = None
depends_on = None


def upgrade():
    op.execute("CREATE EXTENSION IF NOT EXISTS pg_trgm") 
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('ExamPaper', 'hash_code',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('ExamPaper', 'hash_code',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
