"""empty message

Revision ID: c1cecdff31e0
Revises: 28e338e50fb6
Create Date: 2024-05-11 20:47:11.167079

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils
import sqlmodel # added


# revision identifiers, used by Alembic.
revision = 'c1cecdff31e0'
down_revision = '28e338e50fb6'
branch_labels = None
depends_on = None


def upgrade():
    op.execute("CREATE EXTENSION IF NOT EXISTS pg_trgm") 
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('ExamPaper', 'hash_code',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.create_unique_constraint(None, 'ExamPaper', ['hash_code'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'ExamPaper', type_='unique')
    op.alter_column('ExamPaper', 'hash_code',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
