"""empty message

Revision ID: f5fbf91ff434
Revises: 183fdaf0ca84
Create Date: 2024-05-10 18:22:39.317087

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils
import sqlmodel # added


# revision identifiers, used by Alembic.
revision = 'f5fbf91ff434'
down_revision = '183fdaf0ca84'
branch_labels = None
depends_on = None


def upgrade():
    op.execute("CREATE EXTENSION IF NOT EXISTS pg_trgm") 
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ExamDescription',
    sa.Column('id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('slug', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('slug')
    )
    op.create_index(op.f('ix_ExamDescription_id'), 'ExamDescription', ['id'], unique=False)
    op.create_table('ExamTitle',
    sa.Column('id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('slug', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('slug')
    )
    op.create_index(op.f('ix_ExamTitle_id'), 'ExamTitle', ['id'], unique=False)
    op.add_column('ExamPaper', sa.Column('description_id', sqlmodel.sql.sqltypes.GUID(), nullable=True))
    op.add_column('ExamPaper', sa.Column('title_id', sqlmodel.sql.sqltypes.GUID(), nullable=True))
    op.add_column('ExamPaper', sa.Column('institution_id', sqlmodel.sql.sqltypes.GUID(), nullable=True))
    op.drop_constraint('ExamPaper_slug_key', 'ExamPaper', type_='unique')
    op.create_foreign_key(None, 'ExamPaper', 'Institution', ['institution_id'], ['id'])
    op.create_foreign_key(None, 'ExamPaper', 'ExamDescription', ['description_id'], ['id'])
    op.create_foreign_key(None, 'ExamPaper', 'ExamTitle', ['title_id'], ['id'])
    op.drop_column('ExamPaper', 'slug')
    op.drop_column('ExamPaper', 'name')
    op.drop_column('ExamPaper', 'description')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ExamPaper', sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('ExamPaper', sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('ExamPaper', sa.Column('slug', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'ExamPaper', type_='foreignkey')
    op.drop_constraint(None, 'ExamPaper', type_='foreignkey')
    op.drop_constraint(None, 'ExamPaper', type_='foreignkey')
    op.create_unique_constraint('ExamPaper_slug_key', 'ExamPaper', ['slug'])
    op.drop_column('ExamPaper', 'institution_id')
    op.drop_column('ExamPaper', 'title_id')
    op.drop_column('ExamPaper', 'description_id')
    op.drop_index(op.f('ix_ExamTitle_id'), table_name='ExamTitle')
    op.drop_table('ExamTitle')
    op.drop_index(op.f('ix_ExamDescription_id'), table_name='ExamDescription')
    op.drop_table('ExamDescription')
    # ### end Alembic commands ###
