"""empty message

Revision ID: 718fe396e053
Revises: ecf5e578fa98
Create Date: 2024-05-11 21:17:44.976191

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils
import sqlmodel # added


# revision identifiers, used by Alembic.
revision = '718fe396e053'
down_revision = 'ecf5e578fa98'
branch_labels = None
depends_on = None


def upgrade():
    op.execute("CREATE EXTENSION IF NOT EXISTS pg_trgm") 
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('ExamPaper', 'hash_code',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('ExamPaper', 'hash_code',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
