"""empty message

Revision ID: abd77fa99dc9
Revises: 277948cf8522
Create Date: 2024-05-12 12:25:06.920590

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils
import sqlmodel # added


# revision identifiers, used by Alembic.
revision = 'abd77fa99dc9'
down_revision = '277948cf8522'
branch_labels = None
depends_on = None


def upgrade():
    op.execute("CREATE EXTENSION IF NOT EXISTS pg_trgm") 
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('MainQuestion', 'order_within_question_set',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('MainQuestion', 'order_within_question_set',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
