"""empty message

Revision ID: 3330a7e1d348
Revises: 41bb2cecccc9
Create Date: 2024-05-12 20:10:46.279179

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils
import sqlmodel # added


# revision identifiers, used by Alembic.
revision = '3330a7e1d348'
down_revision = '41bb2cecccc9'
branch_labels = None
depends_on = None


def upgrade():
    op.execute("CREATE EXTENSION IF NOT EXISTS pg_trgm") 
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('MainQuestion_order_within_question_set_key', 'MainQuestion', type_='unique')
    op.drop_column('MainQuestion', 'order_within_question_set')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('MainQuestion', sa.Column('order_within_question_set', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.create_unique_constraint('MainQuestion_order_within_question_set_key', 'MainQuestion', ['order_within_question_set'])
    # ### end Alembic commands ###
