"""empty message

Revision ID: a9f49728c7b4
Revises: fb7e27482e8b
Create Date: 2024-05-06 20:10:38.226640

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils
import sqlmodel # added


# revision identifiers, used by Alembic.
revision = 'a9f49728c7b4'
down_revision = 'fb7e27482e8b'
branch_labels = None
depends_on = None


def upgrade():
    op.execute("CREATE EXTENSION IF NOT EXISTS pg_trgm") 
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('InstitutionFacultyLink_created_by_id_fkey', 'InstitutionFacultyLink', type_='foreignkey')
    op.drop_column('InstitutionFacultyLink', 'created_by_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('InstitutionFacultyLink', sa.Column('created_by_id', sa.UUID(), autoincrement=False, nullable=True))
    op.create_foreign_key('InstitutionFacultyLink_created_by_id_fkey', 'InstitutionFacultyLink', 'User', ['created_by_id'], ['id'])
    # ### end Alembic commands ###
