"""empty message

Revision ID: 261406974018
Revises: b97c7b3b14c7
Create Date: 2024-05-07 06:51:19.598726

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils
import sqlmodel # added


# revision identifiers, used by Alembic.
revision = '261406974018'
down_revision = 'b97c7b3b14c7'
branch_labels = None
depends_on = None


def upgrade():
    op.execute("CREATE EXTENSION IF NOT EXISTS pg_trgm") 
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Faculty', sa.Column('institution_count', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Faculty', 'institution_count')
    # ### end Alembic commands ###
