"""empty message

Revision ID: 697b488bb3e5
Revises: 4adc5112ca32
Create Date: 2024-05-06 19:50:59.260255

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils
import sqlmodel # added


# revision identifiers, used by Alembic.
revision = '697b488bb3e5'
down_revision = '4adc5112ca32'
branch_labels = None
depends_on = None


def upgrade():
    op.execute("CREATE EXTENSION IF NOT EXISTS pg_trgm") 
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('InstitutionFacultyLink', sa.Column('created_by_id', sqlmodel.sql.sqltypes.GUID(), nullable=True))
    op.create_foreign_key(None, 'InstitutionFacultyLink', 'User', ['created_by_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'InstitutionFacultyLink', type_='foreignkey')
    op.drop_column('InstitutionFacultyLink', 'created_by_id')
    # ### end Alembic commands ###
