"""empty message

Revision ID: df69776d2e19
Revises: ff483db59fe9
Create Date: 2024-05-12 12:18:19.058252

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils
import sqlmodel # added


# revision identifiers, used by Alembic.
revision = 'df69776d2e19'
down_revision = 'ff483db59fe9'
branch_labels = None
depends_on = None


def upgrade():
    op.execute("CREATE EXTENSION IF NOT EXISTS pg_trgm") 
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('MainQuestion', 'order_within_question_set',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('MainQuestion', 'order_within_question_set',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
