"""empty message

Revision ID: 60175a5892dc
Revises: 0e54eecb0504
Create Date: 2024-05-07 06:57:37.376535

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils
import sqlmodel # added


# revision identifiers, used by Alembic.
revision = '60175a5892dc'
down_revision = '0e54eecb0504'
branch_labels = None
depends_on = None


def upgrade():
    op.execute("CREATE EXTENSION IF NOT EXISTS pg_trgm") 
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Faculty', sa.Column('institution_count', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Faculty', 'institution_count')
    # ### end Alembic commands ###
