"""empty message

Revision ID: cd18fabb743f
Revises: 2d0b923d9c96
Create Date: 2024-05-11 19:36:33.839986

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils
import sqlmodel # added


# revision identifiers, used by Alembic.
revision = 'cd18fabb743f'
down_revision = '2d0b923d9c96'
branch_labels = None
depends_on = None


def upgrade():
    op.execute("CREATE EXTENSION IF NOT EXISTS pg_trgm") 
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ExamPaper', sa.Column('hash_value', sa.String(length=64), nullable=False))
    op.create_unique_constraint(None, 'ExamPaper', ['hash_value'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'ExamPaper', type_='unique')
    op.drop_column('ExamPaper', 'hash_value')
    # ### end Alembic commands ###
