"""empty message

Revision ID: b52a6dd20ff0
Revises: de9630cc4c19
Create Date: 2024-05-10 13:54:54.897179

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils
import sqlmodel # added


# revision identifiers, used by Alembic.
revision = 'b52a6dd20ff0'
down_revision = 'de9630cc4c19'
branch_labels = None
depends_on = None


def upgrade():
    op.execute("CREATE EXTENSION IF NOT EXISTS pg_trgm") 
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ExamInstruction', sa.Column('slug', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.create_unique_constraint(None, 'ExamInstruction', ['slug'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'ExamInstruction', type_='unique')
    op.drop_column('ExamInstruction', 'slug')
    # ### end Alembic commands ###
