"""empty message

Revision ID: 45c099f11e46
Revises: 697b488bb3e5
Create Date: 2024-05-06 19:59:56.830597

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils
import sqlmodel # added


# revision identifiers, used by Alembic.
revision = '45c099f11e46'
down_revision = '697b488bb3e5'
branch_labels = None
depends_on = None


def upgrade():
    op.execute("CREATE EXTENSION IF NOT EXISTS pg_trgm") 
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'InstitutionFacultyLink', ['faculty_id'])
    op.create_unique_constraint(None, 'InstitutionFacultyLink', ['institution_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'InstitutionFacultyLink', type_='unique')
    op.drop_constraint(None, 'InstitutionFacultyLink', type_='unique')
    # ### end Alembic commands ###
