"""empty message

Revision ID: c0129291ffbe
Revises: 
Create Date: 2024-05-06 14:01:22.283751

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils
import sqlmodel # added


# revision identifiers, used by Alembic.
revision = 'c0129291ffbe'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    op.execute("CREATE EXTENSION IF NOT EXISTS pg_trgm") 
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Faculty',
    sa.Column('id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('slug', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_by_id', sqlmodel.sql.sqltypes.GUID(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['User.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('slug')
    )
    op.create_index(op.f('ix_Faculty_id'), 'Faculty', ['id'], unique=False)
    op.create_table('Institution',
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('institution_type', sa.Enum('UNIVERSITY', 'COLLEGE', 'TVET', 'OTHER', name='institutiontypes'), nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('phone_number', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('slug', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('image_id', sqlmodel.sql.sqltypes.GUID(), nullable=True),
    sa.Column('created_by_id', sqlmodel.sql.sqltypes.GUID(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['User.id'], ),
    sa.ForeignKeyConstraint(['image_id'], ['ImageMedia.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('slug')
    )
    op.create_index(op.f('ix_Institution_email'), 'Institution', ['email'], unique=True)
    op.create_index(op.f('ix_Institution_id'), 'Institution', ['id'], unique=False)
    op.create_table('Campus',
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('location', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('slug', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('institution_id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('created_by_id', sqlmodel.sql.sqltypes.GUID(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['User.id'], ),
    sa.ForeignKeyConstraint(['institution_id'], ['Institution.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_index(op.f('ix_Campus_id'), 'Campus', ['id'], unique=False)
    op.create_table('InstitutionFacultyLink',
    sa.Column('id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('institution_id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('faculty_id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.ForeignKeyConstraint(['faculty_id'], ['Faculty.id'], ),
    sa.ForeignKeyConstraint(['institution_id'], ['Institution.id'], ),
    sa.PrimaryKeyConstraint('id', 'institution_id', 'faculty_id')
    )
    op.create_index(op.f('ix_InstitutionFacultyLink_id'), 'InstitutionFacultyLink', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_InstitutionFacultyLink_id'), table_name='InstitutionFacultyLink')
    op.drop_table('InstitutionFacultyLink')
    op.drop_index(op.f('ix_Campus_id'), table_name='Campus')
    op.drop_table('Campus')
    op.drop_index(op.f('ix_Institution_id'), table_name='Institution')
    op.drop_index(op.f('ix_Institution_email'), table_name='Institution')
    op.drop_table('Institution')
    op.drop_index(op.f('ix_Faculty_id'), table_name='Faculty')
    op.drop_table('Faculty')
    # ### end Alembic commands ###
