"""empty message

Revision ID: b35ee9919025
Revises: 6f9b3507a919
Create Date: 2024-12-14 08:55:48.217478

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils
import sqlmodel # added


# revision identifiers, used by Alembic.
revision = 'b35ee9919025'
down_revision = '6f9b3507a919'
branch_labels = None
depends_on = None


def upgrade():
    op.execute("CREATE EXTENSION IF NOT EXISTS pg_trgm") 
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Course', sa.Column('course_acronym', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.create_unique_constraint(None, 'Course', ['course_acronym'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'Course', type_='unique')
    op.drop_column('Course', 'course_acronym')
    # ### end Alembic commands ###
