"""empty message

Revision ID: 7ad0bcffef57
Revises: 94f2999d2d58
Create Date: 2024-05-12 11:06:54.005947

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils
import sqlmodel # added


# revision identifiers, used by Alembic.
revision = '7ad0bcffef57'
down_revision = '94f2999d2d58'
branch_labels = None
depends_on = None


def upgrade():
    op.execute("CREATE EXTENSION IF NOT EXISTS pg_trgm") 
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('_exam_paper_question_set_uc', 'ExamPaperQuestionLink', ['exam_id', 'question_set_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('_exam_paper_question_set_uc', 'ExamPaperQuestionLink', type_='unique')
    # ### end Alembic commands ###
