"""empty message

Revision ID: c24415ae256d
Revises: 2820cfb98e64
Create Date: 2024-05-12 12:39:03.601298

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils
import sqlmodel # added


# revision identifiers, used by Alembic.
revision = 'c24415ae256d'
down_revision = '2820cfb98e64'
branch_labels = None
depends_on = None


def upgrade():
    op.execute("CREATE EXTENSION IF NOT EXISTS pg_trgm") 
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'MainQuestion', ['order_within_question_set'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'MainQuestion', type_='unique')
    # ### end Alembic commands ###
