"""empty message

Revision ID: 4f066a4f8bba
Revises: 5668b98b64ae
Create Date: 2024-05-08 10:31:26.667033

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils
import sqlmodel # added


# revision identifiers, used by Alembic.
revision = '4f066a4f8bba'
down_revision = '5668b98b64ae'
branch_labels = None
depends_on = None


def upgrade():
    op.execute("CREATE EXTENSION IF NOT EXISTS pg_trgm") 
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'Campus', ['address'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'Campus', type_='unique')
    # ### end Alembic commands ###
