"""empty message

Revision ID: bee194a2fe98
Revises: e816a396ad6c
Create Date: 2024-05-12 12:20:14.504885

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils
import sqlmodel # added


# revision identifiers, used by Alembic.
revision = 'bee194a2fe98'
down_revision = 'e816a396ad6c'
branch_labels = None
depends_on = None


def upgrade():
    op.execute("CREATE EXTENSION IF NOT EXISTS pg_trgm") 
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'MainQuestion', ['order_within_question_set'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'MainQuestion', type_='unique')
    # ### end Alembic commands ###
