"""empty message

Revision ID: b97c7b3b14c7
Revises: ac9063113e1e
Create Date: 2024-05-07 06:46:07.582799

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils
import sqlmodel # added


# revision identifiers, used by Alembic.
revision = 'b97c7b3b14c7'
down_revision = 'ac9063113e1e'
branch_labels = None
depends_on = None


def upgrade():
    op.execute("CREATE EXTENSION IF NOT EXISTS pg_trgm") 
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Faculty', 'institution_count')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Faculty', sa.Column('institution_count', sa.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
