"""empty message

Revision ID: 4af936db7a0d
Revises: 5288bbe98986
Create Date: 2024-05-10 18:55:43.220303

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils
import sqlmodel # added


# revision identifiers, used by Alembic.
revision = '4af936db7a0d'
down_revision = '5288bbe98986'
branch_labels = None
depends_on = None


def upgrade():
    op.execute("CREATE EXTENSION IF NOT EXISTS pg_trgm") 
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ExamDescription', sa.Column('created_by_id', sqlmodel.sql.sqltypes.GUID(), nullable=True))
    op.create_foreign_key(None, 'ExamDescription', 'User', ['created_by_id'], ['id'])
    op.add_column('ExamTitle', sa.Column('created_by_id', sqlmodel.sql.sqltypes.GUID(), nullable=True))
    op.create_foreign_key(None, 'ExamTitle', 'User', ['created_by_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'ExamTitle', type_='foreignkey')
    op.drop_column('ExamTitle', 'created_by_id')
    op.drop_constraint(None, 'ExamDescription', type_='foreignkey')
    op.drop_column('ExamDescription', 'created_by_id')
    # ### end Alembic commands ###
