"""empty message

Revision ID: 83d8646bfd28
Revises: da230cb3a71f
Create Date: 2024-05-10 19:35:43.518642

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils
import sqlmodel # added


# revision identifiers, used by Alembic.
revision = '83d8646bfd28'
down_revision = 'da230cb3a71f'
branch_labels = None
depends_on = None


def upgrade():
    op.execute("CREATE EXTENSION IF NOT EXISTS pg_trgm") 
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ExamInstruction', sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.drop_constraint('ExamInstruction_instruction_text_key', 'ExamInstruction', type_='unique')
    op.create_unique_constraint(None, 'ExamInstruction', ['name'])
    op.drop_column('ExamInstruction', 'instruction_text')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ExamInstruction', sa.Column('instruction_text', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'ExamInstruction', type_='unique')
    op.create_unique_constraint('ExamInstruction_instruction_text_key', 'ExamInstruction', ['instruction_text'])
    op.drop_column('ExamInstruction', 'name')
    # ### end Alembic commands ###
