"""empty message

Revision ID: 62c86886c986
Revises: b50a6714eed7
Create Date: 2025-04-12 10:47:13.966572

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils
import sqlmodel # added


# revision identifiers, used by Alembic.
revision = '62c86886c986'
down_revision = 'b50a6714eed7'
branch_labels = None
depends_on = None


def upgrade():
    op.execute("CREATE EXTENSION IF NOT EXISTS pg_trgm") 
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Department', sa.Column('programmes_count', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Department', 'programmes_count')
    # ### end Alembic commands ###
