"""Add slug to ExamPaper identifying name

Revision ID: 7e0ee28955c1
Revises: 86a55bc34d01
Create Date: 2025-10-06 17:32:47.302146

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils
import sqlmodel # added


# revision identifiers, used by Alembic.
revision = '7e0ee28955c1'
down_revision = '86a55bc34d01'
branch_labels = None
depends_on = None


def upgrade():
    op.execute("CREATE EXTENSION IF NOT EXISTS pg_trgm") 
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
