"""empty message

Revision ID: 7179e675e30b
Revises: 62c86886c986
Create Date: 2025-04-12 10:48:29.720856

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils
import sqlmodel # added


# revision identifiers, used by Alembic.
revision = '7179e675e30b'
down_revision = '62c86886c986'
branch_labels = None
depends_on = None


def upgrade():
    op.execute("CREATE EXTENSION IF NOT EXISTS pg_trgm") 
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Department', 'programmes_count')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Department', sa.Column('programmes_count', sa.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
