"""add faculty relationship to course

Revision ID: b00208279b5e
Revises: 4b2e7f775483
Create Date: 2025-12-03 17:07:59.302524

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils
import sqlmodel # added


# revision identifiers, used by Alembic.
revision = 'b00208279b5e'
down_revision = '4b2e7f775483'
branch_labels = None
depends_on = None


def upgrade():
    op.execute("CREATE EXTENSION IF NOT EXISTS pg_trgm") 
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('Course_course_acronym_key', 'Course', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('Course_course_acronym_key', 'Course', ['course_acronym'])
    # ### end Alembic commands ###
