"""empty message

Revision ID: 83349a9669b9
Revises: b35ee9919025
Create Date: 2025-03-05 08:59:31.419412

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils
import sqlmodel # added


# revision identifiers, used by Alembic.
revision = '83349a9669b9'
down_revision = 'b35ee9919025'
branch_labels = None
depends_on = None


def upgrade():
    op.execute("CREATE EXTENSION IF NOT EXISTS pg_trgm") 
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ExamPaper', sa.Column('instruction_ids', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ExamPaper', 'instruction_ids')
    # ### end Alembic commands ###
