"""empty message

Revision ID: 75642aaed02d
Revises: 3f0a610daa58
Create Date: 2025-03-31 22:37:28.099816

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils
import sqlmodel # added


# revision identifiers, used by Alembic.
revision = '75642aaed02d'
down_revision = '3f0a610daa58'
branch_labels = None
depends_on = None


def upgrade():
    op.execute("CREATE EXTENSION IF NOT EXISTS pg_trgm") 
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_Institution_description'), 'Institution', ['description'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_Institution_description'), table_name='Institution')
    # ### end Alembic commands ###
