"""empty message

Revision ID: 51669d321625
Revises: af80caba3781
Create Date: 2025-04-13 16:12:04.800907

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils
import sqlmodel # added


# revision identifiers, used by Alembic.
revision = '51669d321625'
down_revision = 'af80caba3781'
branch_labels = None
depends_on = None


def upgrade():
    op.execute("CREATE EXTENSION IF NOT EXISTS pg_trgm") 
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ExamPaper', sa.Column('hash_code', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.create_unique_constraint(None, 'ExamPaper', ['hash_code'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'ExamPaper', type_='unique')
    op.drop_column('ExamPaper', 'hash_code')
    # ### end Alembic commands ###
