"""empty message

Revision ID: b08e6e576247
Revises: d917ff201408
Create Date: 2025-03-21 14:57:25.456687

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils
import sqlmodel # added


# revision identifiers, used by Alembic.
revision = 'b08e6e576247'
down_revision = 'd917ff201408'
branch_labels = None
depends_on = None


def upgrade():
    op.execute("CREATE EXTENSION IF NOT EXISTS pg_trgm") 
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('SubQuestion', sa.Column('numbering_style', sa.Enum('ROMAN', 'ALPHA', name='numberingstyleenum', native_enum=False), nullable=True))
    op.add_column('SubQuestion', sa.Column('question_number', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('SubQuestion', 'question_number')
    op.drop_column('SubQuestion', 'numbering_style')
    # ### end Alembic commands ###
