"""empty message

Revision ID: 419c4ef1465e
Revises: 6b7756489da0
Create Date: 2025-03-22 22:49:50.038901

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils
import sqlmodel # added


# revision identifiers, used by Alembic.
revision = '419c4ef1465e'
down_revision = '6b7756489da0'
branch_labels = None
depends_on = None


def upgrade():
    op.execute("CREATE EXTENSION IF NOT EXISTS pg_trgm") 
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('Answer_child_id_fkey', 'Answer', type_='foreignkey')
    op.drop_column('Answer', 'child_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Answer', sa.Column('child_id', sa.UUID(), autoincrement=False, nullable=True))
    op.create_foreign_key('Answer_child_id_fkey', 'Answer', 'Answer', ['child_id'], ['id'])
    # ### end Alembic commands ###
