"""Add slug to ExamPaper

Revision ID: 1b8b13c24c9e
Revises: 33fba72510ba
Create Date: 2025-10-06 17:06:14.335751

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils
import sqlmodel # added


# revision identifiers, used by Alembic.
revision = '1b8b13c24c9e'
down_revision = '33fba72510ba'
branch_labels = None
depends_on = None


def upgrade():
    op.execute("CREATE EXTENSION IF NOT EXISTS pg_trgm") 
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ExamPaper', sa.Column('identifying_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ExamPaper', 'identifying_name')
    # ### end Alembic commands ###
