"""empty message

Revision ID: 3f0a610daa58
Revises: eada8f20e3e1
Create Date: 2025-03-31 22:20:09.304891

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils
import sqlmodel # added


# revision identifiers, used by Alembic.
revision = '3f0a610daa58'
down_revision = 'eada8f20e3e1'
branch_labels = None
depends_on = None


def upgrade():
    op.execute("CREATE EXTENSION IF NOT EXISTS pg_trgm") 
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_Answer_created_at'), 'Answer', ['created_at'], unique=False)
    op.create_index(op.f('ix_Campus_created_at'), 'Campus', ['created_at'], unique=False)
    op.create_index(op.f('ix_Comment_created_at'), 'Comment', ['created_at'], unique=False)
    op.create_index(op.f('ix_Course_created_at'), 'Course', ['created_at'], unique=False)
    op.create_index(op.f('ix_CourseModuleLink_created_at'), 'CourseModuleLink', ['created_at'], unique=False)
    op.create_index(op.f('ix_Department_created_at'), 'Department', ['created_at'], unique=False)
    op.create_index(op.f('ix_ExamDescription_created_at'), 'ExamDescription', ['created_at'], unique=False)
    op.create_index(op.f('ix_ExamInstruction_created_at'), 'ExamInstruction', ['created_at'], unique=False)
    op.create_index(op.f('ix_ExamPaper_created_at'), 'ExamPaper', ['created_at'], unique=False)
    op.create_index(op.f('ix_ExamPaperQuestionLink_created_at'), 'ExamPaperQuestionLink', ['created_at'], unique=False)
    op.create_index(op.f('ix_ExamTitle_created_at'), 'ExamTitle', ['created_at'], unique=False)
    op.create_index(op.f('ix_Faculty_created_at'), 'Faculty', ['created_at'], unique=False)
    op.create_index(op.f('ix_Group_created_at'), 'Group', ['created_at'], unique=False)
    op.create_index(op.f('ix_Hero_created_at'), 'Hero', ['created_at'], unique=False)
    op.create_index(op.f('ix_ImageMedia_created_at'), 'ImageMedia', ['created_at'], unique=False)
    op.drop_constraint('Institution_name_key', 'Institution', type_='unique')
    op.drop_constraint('Institution_slug_key', 'Institution', type_='unique')
    op.create_index('idx_institution_created_at', 'Institution', ['created_at'], unique=False)
    op.create_index('idx_institution_created_by_id', 'Institution', ['created_by_id'], unique=False)
    op.create_index('idx_institution_email', 'Institution', ['email'], unique=False)
    op.create_index('idx_institution_image_id', 'Institution', ['image_id'], unique=False)
    op.create_index('idx_institution_name', 'Institution', ['name'], unique=False)
    op.create_index('idx_institution_slug', 'Institution', ['slug'], unique=False)
    op.create_index('idx_institution_type', 'Institution', ['institution_type'], unique=False)
    op.create_index(op.f('ix_Institution_created_at'), 'Institution', ['created_at'], unique=False)
    op.create_index(op.f('ix_Institution_created_by_id'), 'Institution', ['created_by_id'], unique=False)
    op.create_index(op.f('ix_Institution_name'), 'Institution', ['name'], unique=True)
    op.create_index(op.f('ix_Institution_slug'), 'Institution', ['slug'], unique=True)
    op.create_index(op.f('ix_InstitutionFacultyLink_created_at'), 'InstitutionFacultyLink', ['created_at'], unique=False)
    op.create_index(op.f('ix_InstructionExamsLink_created_at'), 'InstructionExamsLink', ['created_at'], unique=False)
    op.create_index(op.f('ix_LinkGroupUser_created_at'), 'LinkGroupUser', ['created_at'], unique=False)
    op.create_index(op.f('ix_MainQuestion_created_at'), 'MainQuestion', ['created_at'], unique=False)
    op.create_index(op.f('ix_Media_created_at'), 'Media', ['created_at'], unique=False)
    op.create_index(op.f('ix_Module_created_at'), 'Module', ['created_at'], unique=False)
    op.create_index(op.f('ix_ModuleExamsLink_created_at'), 'ModuleExamsLink', ['created_at'], unique=False)
    op.create_index(op.f('ix_Programme_created_at'), 'Programme', ['created_at'], unique=False)
    op.create_index(op.f('ix_ProgrammeDepartmentLink_created_at'), 'ProgrammeDepartmentLink', ['created_at'], unique=False)
    op.create_index(op.f('ix_QuestionSet_created_at'), 'QuestionSet', ['created_at'], unique=False)
    op.create_index(op.f('ix_Role_created_at'), 'Role', ['created_at'], unique=False)
    op.create_index(op.f('ix_SubQuestion_created_at'), 'SubQuestion', ['created_at'], unique=False)
    op.create_index(op.f('ix_Team_created_at'), 'Team', ['created_at'], unique=False)
    op.create_index(op.f('ix_User_created_at'), 'User', ['created_at'], unique=False)
    op.create_index(op.f('ix_UserFollow_created_at'), 'UserFollow', ['created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_UserFollow_created_at'), table_name='UserFollow')
    op.drop_index(op.f('ix_User_created_at'), table_name='User')
    op.drop_index(op.f('ix_Team_created_at'), table_name='Team')
    op.drop_index(op.f('ix_SubQuestion_created_at'), table_name='SubQuestion')
    op.drop_index(op.f('ix_Role_created_at'), table_name='Role')
    op.drop_index(op.f('ix_QuestionSet_created_at'), table_name='QuestionSet')
    op.drop_index(op.f('ix_ProgrammeDepartmentLink_created_at'), table_name='ProgrammeDepartmentLink')
    op.drop_index(op.f('ix_Programme_created_at'), table_name='Programme')
    op.drop_index(op.f('ix_ModuleExamsLink_created_at'), table_name='ModuleExamsLink')
    op.drop_index(op.f('ix_Module_created_at'), table_name='Module')
    op.drop_index(op.f('ix_Media_created_at'), table_name='Media')
    op.drop_index(op.f('ix_MainQuestion_created_at'), table_name='MainQuestion')
    op.drop_index(op.f('ix_LinkGroupUser_created_at'), table_name='LinkGroupUser')
    op.drop_index(op.f('ix_InstructionExamsLink_created_at'), table_name='InstructionExamsLink')
    op.drop_index(op.f('ix_InstitutionFacultyLink_created_at'), table_name='InstitutionFacultyLink')
    op.drop_index(op.f('ix_Institution_slug'), table_name='Institution')
    op.drop_index(op.f('ix_Institution_name'), table_name='Institution')
    op.drop_index(op.f('ix_Institution_created_by_id'), table_name='Institution')
    op.drop_index(op.f('ix_Institution_created_at'), table_name='Institution')
    op.drop_index('idx_institution_type', table_name='Institution')
    op.drop_index('idx_institution_slug', table_name='Institution')
    op.drop_index('idx_institution_name', table_name='Institution')
    op.drop_index('idx_institution_image_id', table_name='Institution')
    op.drop_index('idx_institution_email', table_name='Institution')
    op.drop_index('idx_institution_created_by_id', table_name='Institution')
    op.drop_index('idx_institution_created_at', table_name='Institution')
    op.create_unique_constraint('Institution_slug_key', 'Institution', ['slug'])
    op.create_unique_constraint('Institution_name_key', 'Institution', ['name'])
    op.drop_index(op.f('ix_ImageMedia_created_at'), table_name='ImageMedia')
    op.drop_index(op.f('ix_Hero_created_at'), table_name='Hero')
    op.drop_index(op.f('ix_Group_created_at'), table_name='Group')
    op.drop_index(op.f('ix_Faculty_created_at'), table_name='Faculty')
    op.drop_index(op.f('ix_ExamTitle_created_at'), table_name='ExamTitle')
    op.drop_index(op.f('ix_ExamPaperQuestionLink_created_at'), table_name='ExamPaperQuestionLink')
    op.drop_index(op.f('ix_ExamPaper_created_at'), table_name='ExamPaper')
    op.drop_index(op.f('ix_ExamInstruction_created_at'), table_name='ExamInstruction')
    op.drop_index(op.f('ix_ExamDescription_created_at'), table_name='ExamDescription')
    op.drop_index(op.f('ix_Department_created_at'), table_name='Department')
    op.drop_index(op.f('ix_CourseModuleLink_created_at'), table_name='CourseModuleLink')
    op.drop_index(op.f('ix_Course_created_at'), table_name='Course')
    op.drop_index(op.f('ix_Comment_created_at'), table_name='Comment')
    op.drop_index(op.f('ix_Campus_created_at'), table_name='Campus')
    op.drop_index(op.f('ix_Answer_created_at'), table_name='Answer')
    # ### end Alembic commands ###
