"""Add slug to ExamPaper

Revision ID: 86a55bc34d01
Revises: 1b8b13c24c9e
Create Date: 2025-10-06 17:30:14.811793

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils
import sqlmodel # added


# revision identifiers, used by Alembic.
revision = '86a55bc34d01'
down_revision = '1b8b13c24c9e'
branch_labels = None
depends_on = None


def upgrade():
    op.execute("CREATE EXTENSION IF NOT EXISTS pg_trgm") 
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
