"""empty message

Revision ID: 02540d9e2fd1
Revises: 69fd6228a77b
Create Date: 2025-03-05 20:12:00.786789

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils
import sqlmodel # added
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '02540d9e2fd1'
down_revision = '69fd6228a77b'
branch_labels = None
depends_on = None


def upgrade():
    op.execute("CREATE EXTENSION IF NOT EXISTS pg_trgm") 
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ExamPaper', 'module_ids')
    op.drop_column('ExamPaper', 'instruction_ids')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ExamPaper', sa.Column('instruction_ids', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('ExamPaper', sa.Column('module_ids', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
