"""empty message

Revision ID: 6e5544b5e527
Revises: 8f2e75485e09
Create Date: 2025-04-13 15:58:20.809842

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils
import sqlmodel # added


# revision identifiers, used by Alembic.
revision = '6e5544b5e527'
down_revision = '8f2e75485e09'
branch_labels = None
depends_on = None


def upgrade():
    op.execute("CREATE EXTENSION IF NOT EXISTS pg_trgm") 
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ExamPaper', 'identifying_name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ExamPaper', sa.Column('identifying_name', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
