"""empty message

Revision ID: 0d6e9095c44b
Revises: 8c7c1ee16048
Create Date: 2025-04-11 10:56:36.511864

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils
import sqlmodel # added


# revision identifiers, used by Alembic.
revision = '0d6e9095c44b'
down_revision = '8c7c1ee16048'
branch_labels = None
depends_on = None


def upgrade():
    op.execute("CREATE EXTENSION IF NOT EXISTS pg_trgm") 
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_institution_created_at', table_name='Institution')
    op.drop_index('idx_institution_created_by_id', table_name='Institution')
    op.drop_index('idx_institution_email', table_name='Institution')
    op.drop_index('idx_institution_image_id', table_name='Institution')
    op.drop_index('idx_institution_name', table_name='Institution')
    op.drop_index('idx_institution_slug', table_name='Institution')
    op.drop_index('idx_institution_type', table_name='Institution')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_institution_type', 'Institution', ['institution_type'], unique=False)
    op.create_index('idx_institution_slug', 'Institution', ['slug'], unique=False)
    op.create_index('idx_institution_name', 'Institution', ['name'], unique=False)
    op.create_index('idx_institution_image_id', 'Institution', ['image_id'], unique=False)
    op.create_index('idx_institution_email', 'Institution', ['email'], unique=False)
    op.create_index('idx_institution_created_by_id', 'Institution', ['created_by_id'], unique=False)
    op.create_index('idx_institution_created_at', 'Institution', ['created_at'], unique=False)
    # ### end Alembic commands ###
