"""Add slug to ExamPaper identifying name

Revision ID: 16b1a52b7e35
Revises: b415bb512d89
Create Date: 2025-10-06 17:46:07.264323

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils
import sqlmodel # added


# revision identifiers, used by Alembic.
revision = '16b1a52b7e35'
down_revision = 'b415bb512d89'
branch_labels = None
depends_on = None


def upgrade():
    op.execute("CREATE EXTENSION IF NOT EXISTS pg_trgm") 
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ExamPaper', 'identifying_name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ExamPaper', sa.Column('identifying_name', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
