"""empty message

Revision ID: 41cce28737f1
Revises: 0d6e9095c44b
Create Date: 2025-04-11 11:27:24.731642

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils
import sqlmodel # added


# revision identifiers, used by Alembic.
revision = '41cce28737f1'
down_revision = '0d6e9095c44b'
branch_labels = None
depends_on = None


def upgrade():
    op.execute("CREATE EXTENSION IF NOT EXISTS pg_trgm") 
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_institution_created_at', 'Institution', ['created_at'], unique=False)
    op.create_index('idx_institution_name', 'Institution', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_institution_name', table_name='Institution')
    op.drop_index('idx_institution_created_at', table_name='Institution')
    # ### end Alembic commands ###
