"""empty message

Revision ID: 1cf9c4f91f3d
Revises: 38bbd133e5fa
Create Date: 2025-04-16 13:20:52.895631

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils
import sqlmodel # added


# revision identifiers, used by Alembic.
revision = '1cf9c4f91f3d'
down_revision = '38bbd133e5fa'
branch_labels = None
depends_on = None


def upgrade():
    op.execute("CREATE EXTENSION IF NOT EXISTS pg_trgm") 
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Institution', 'phone_number',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.create_index('ix_module_description', 'Module', ['description'], unique=False)
    op.create_index('ix_module_name', 'Module', ['name'], unique=False)
    op.create_index('ix_module_unit_code', 'Module', ['unit_code'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_module_unit_code', table_name='Module')
    op.drop_index('ix_module_name', table_name='Module')
    op.drop_index('ix_module_description', table_name='Module')
    op.alter_column('Institution', 'phone_number',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
