"""unique_question_set_and_enums

Revision ID: 926b40094958
Revises: b00208279b5e
Create Date: 2025-12-25 14:49:19.687034

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils
import sqlmodel # added


# revision identifiers, used by Alembic.
revision = '926b40094958'
down_revision = 'b00208279b5e'
branch_labels = None
depends_on = None


def upgrade():
    op.execute("CREATE EXTENSION IF NOT EXISTS pg_trgm") 
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'QuestionSet', ['title'])
    op.create_unique_constraint(None, 'QuestionSet', ['slug'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'QuestionSet', type_='unique')
    op.drop_constraint(None, 'QuestionSet', type_='unique')
    # ### end Alembic commands ###
