"""update institution category enum

Revision ID: 33764398070b
Revises: e953d26cc2b0
Create Date: 2025-11-28 16:10:03.949912

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils
import sqlmodel # added


# revision identifiers, used by Alembic.
revision = '33764398070b'
down_revision = 'e953d26cc2b0'
branch_labels = None
depends_on = None


def upgrade():
    op.execute("CREATE EXTENSION IF NOT EXISTS pg_trgm") 
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('ExamPaper', 'hash_code',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.create_unique_constraint(None, 'ExamPaper', ['hash_code'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'ExamPaper', type_='unique')
    op.alter_column('ExamPaper', 'hash_code',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
