"""empty message

Revision ID: 10b3fa9142de
Revises: 22263d59821b
Create Date: 2025-03-06 10:33:20.728656

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils
import sqlmodel # added


# revision identifiers, used by Alembic.
revision = '10b3fa9142de'
down_revision = '22263d59821b'
branch_labels = None
depends_on = None


def upgrade():
    op.execute("CREATE EXTENSION IF NOT EXISTS pg_trgm") 
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'QuestionSet', ['title'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'QuestionSet', type_='unique')
    # ### end Alembic commands ###
