"""add faculty relationship to course

Revision ID: 231526205581
Revises: 8fe239c98021
Create Date: 2025-10-24 10:14:53.291603

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils
import sqlmodel # added


# revision identifiers, used by Alembic.
revision = '231526205581'
down_revision = '8fe239c98021'
branch_labels = None
depends_on = None


def upgrade():
    op.execute("CREATE EXTENSION IF NOT EXISTS pg_trgm") 
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('QuestionSet_slug_key', 'QuestionSet', type_='unique')
    op.drop_constraint('QuestionSet_title_key', 'QuestionSet', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('QuestionSet_title_key', 'QuestionSet', ['title'])
    op.create_unique_constraint('QuestionSet_slug_key', 'QuestionSet', ['slug'])
    # ### end Alembic commands ###
