"""empty message

Revision ID: dda2cfd73c04
Revises: 83349a9669b9
Create Date: 2025-03-05 09:24:18.129401

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils
import sqlmodel # added


# revision identifiers, used by Alembic.
revision = 'dda2cfd73c04'
down_revision = '83349a9669b9'
branch_labels = None
depends_on = None


def upgrade():
    op.execute("CREATE EXTENSION IF NOT EXISTS pg_trgm") 
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ExamPaper', sa.Column('module_ids', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ExamPaper', 'module_ids')
    # ### end Alembic commands ###
