"""add faculty relationship to course

Revision ID: e953d26cc2b0
Revises: cc2899eb87e1
Create Date: 2025-11-05 20:04:01.157555

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils
import sqlmodel # added


# revision identifiers, used by Alembic.
revision = 'e953d26cc2b0'
down_revision = 'cc2899eb87e1'
branch_labels = None
depends_on = None


def upgrade():
    op.execute("CREATE EXTENSION IF NOT EXISTS pg_trgm") 
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('AnswerVote',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('answer_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('vote_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['answer_id'], ['Answer.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['User.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('answer_id', 'user_id', name='_answer_user_vote_uc')
    )
    op.create_index(op.f('ix_AnswerVote_id'), 'AnswerVote', ['id'], unique=False)
    op.alter_column('Question', 'numbering_style',
               existing_type=sa.VARCHAR(length=5),
               type_=sa.Enum('ROMAN', 'ALPHA', 'NUMERICAL', name='numberingstyleenum', native_enum=False),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Question', 'numbering_style',
               existing_type=sa.Enum('ROMAN', 'ALPHA', 'NUMERICAL', name='numberingstyleenum', native_enum=False),
               type_=sa.VARCHAR(length=5),
               existing_nullable=False)
    op.drop_index(op.f('ix_AnswerVote_id'), table_name='AnswerVote')
    op.drop_table('AnswerVote')
    # ### end Alembic commands ###
