"""empty message

Revision ID: 6b7756489da0
Revises: bbf799125e01
Create Date: 2025-03-22 22:47:24.339704

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils
import sqlmodel # added


# revision identifiers, used by Alembic.
revision = '6b7756489da0'
down_revision = 'bbf799125e01'
branch_labels = None
depends_on = None


def upgrade():
    op.execute("CREATE EXTENSION IF NOT EXISTS pg_trgm") 
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Answer', sa.Column('child_id', sqlmodel.sql.sqltypes.GUID(), nullable=True))
    op.create_foreign_key(None, 'Answer', 'Answer', ['child_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'Answer', type_='foreignkey')
    op.drop_column('Answer', 'child_id')
    # ### end Alembic commands ###
