"""empty message

Revision ID: 193213c7d3a0
Revises: 7179e675e30b
Create Date: 2025-04-13 15:26:02.514229

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils
import sqlmodel # added


# revision identifiers, used by Alembic.
revision = '193213c7d3a0'
down_revision = '7179e675e30b'
branch_labels = None
depends_on = None


def upgrade():
    op.execute("CREATE EXTENSION IF NOT EXISTS pg_trgm") 
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ExamPaper', sa.Column('identifying_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.drop_constraint('ExamPaper_hash_code_key', 'ExamPaper', type_='unique')
    op.drop_column('ExamPaper', 'hash_code')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ExamPaper', sa.Column('hash_code', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.create_unique_constraint('ExamPaper_hash_code_key', 'ExamPaper', ['hash_code'])
    op.drop_column('ExamPaper', 'identifying_name')
    # ### end Alembic commands ###
