"""Add slug to ExamPaper

Revision ID: 33fba72510ba
Revises: 6335cab6819a
Create Date: 2025-10-06 16:01:40.446554

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils
import sqlmodel # added


# revision identifiers, used by Alembic.
revision = '33fba72510ba'
down_revision = '6335cab6819a'
branch_labels = None
depends_on = None


def upgrade():
    op.execute("CREATE EXTENSION IF NOT EXISTS pg_trgm") 
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ExamPaper', sa.Column('slug', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ExamPaper', 'slug')
    # ### end Alembic commands ###
