"""empty message

Revision ID: f74a887122f8
Revises: 06f77fd42e76
Create Date: 2025-04-11 10:22:29.389836

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils
import sqlmodel # added


# revision identifiers, used by Alembic.
revision = 'f74a887122f8'
down_revision = '06f77fd42e76'
branch_labels = None
depends_on = None


def upgrade():
    op.execute("CREATE EXTENSION IF NOT EXISTS pg_trgm") 
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_Institution_description', table_name='Institution')
    op.drop_index('ix_Institution_email', table_name='Institution')
    op.drop_index('ix_Institution_name', table_name='Institution')
    op.drop_index('ix_Institution_slug', table_name='Institution')
    op.create_unique_constraint(None, 'Institution', ['email'])
    op.create_unique_constraint(None, 'Institution', ['name'])
    op.create_unique_constraint(None, 'Institution', ['slug'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'Institution', type_='unique')
    op.drop_constraint(None, 'Institution', type_='unique')
    op.drop_constraint(None, 'Institution', type_='unique')
    op.create_index('ix_Institution_slug', 'Institution', ['slug'], unique=True)
    op.create_index('ix_Institution_name', 'Institution', ['name'], unique=True)
    op.create_index('ix_Institution_email', 'Institution', ['email'], unique=True)
    op.create_index('ix_Institution_description', 'Institution', ['description'], unique=False)
    # ### end Alembic commands ###
