"""Add audit_log and activity_log tables

Revision ID: 4b2e7f775483
Revises: b3b8cf309be8
Create Date: 2025-11-30 21:24:37.927790

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils
import sqlmodel # added


# revision identifiers, used by Alembic.
revision = '4b2e7f775483'
down_revision = 'b3b8cf309be8'
branch_labels = None
depends_on = None


def upgrade():
    op.execute("CREATE EXTENSION IF NOT EXISTS pg_trgm") 
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ActivityLog',
    sa.Column('user_id', sa.Uuid(), nullable=True),
    sa.Column('method', sa.String(length=10), nullable=False),
    sa.Column('endpoint', sa.String(length=500), nullable=False),
    sa.Column('path', sa.String(length=500), nullable=False),
    sa.Column('query_params', sa.JSON(), nullable=True),
    sa.Column('status_code', sa.Integer(), nullable=False),
    sa.Column('response_time_ms', sa.Float(), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.String(length=500), nullable=True),
    sa.Column('request_id', sa.String(length=100), nullable=True),
    sa.Column('details', sa.JSON(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['User.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ActivityLog_endpoint'), 'ActivityLog', ['endpoint'], unique=False)
    op.create_index(op.f('ix_ActivityLog_id'), 'ActivityLog', ['id'], unique=False)
    op.create_index(op.f('ix_ActivityLog_request_id'), 'ActivityLog', ['request_id'], unique=False)
    op.create_index(op.f('ix_ActivityLog_user_id'), 'ActivityLog', ['user_id'], unique=False)
    op.create_index('ix_activitylog_created_at', 'ActivityLog', ['created_at'], unique=False)
    op.create_index('ix_activitylog_status', 'ActivityLog', ['status_code'], unique=False)
    op.create_index('ix_activitylog_user_endpoint', 'ActivityLog', ['user_id', 'endpoint'], unique=False)
    op.create_table('AuditLog',
    sa.Column('user_id', sa.Uuid(), nullable=True),
    sa.Column('action', sa.Enum('LOGIN_SUCCESS', 'LOGIN_FAILED', 'LOGOUT', 'TOKEN_REFRESH', 'PASSWORD_CHANGED', 'PASSWORD_RESET_REQUESTED', 'PASSWORD_RESET_COMPLETED', 'ACCOUNT_CREATED', 'ACCOUNT_UPDATED', 'ACCOUNT_DEACTIVATED', 'ACCOUNT_REACTIVATED', 'ACCOUNT_LOCKED', 'ACCOUNT_UNLOCKED', 'PERMISSION_DENIED', 'ROLE_CHANGED', 'DATA_CREATED', 'DATA_UPDATED', 'DATA_DELETED', 'DATA_EXPORTED', 'ADMIN_ACTION', 'SYSTEM_CONFIG_CHANGED', name='auditactiontype'), nullable=False),
    sa.Column('resource_type', sa.String(length=100), nullable=True),
    sa.Column('resource_id', sa.String(length=100), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.String(length=500), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('details', sa.JSON(), nullable=True),
    sa.Column('success', sa.Boolean(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['User.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_AuditLog_action'), 'AuditLog', ['action'], unique=False)
    op.create_index(op.f('ix_AuditLog_email'), 'AuditLog', ['email'], unique=False)
    op.create_index(op.f('ix_AuditLog_id'), 'AuditLog', ['id'], unique=False)
    op.create_index(op.f('ix_AuditLog_resource_type'), 'AuditLog', ['resource_type'], unique=False)
    op.create_index(op.f('ix_AuditLog_user_id'), 'AuditLog', ['user_id'], unique=False)
    op.create_index('ix_auditlog_created_at', 'AuditLog', ['created_at'], unique=False)
    op.create_index('ix_auditlog_resource', 'AuditLog', ['resource_type', 'resource_id'], unique=False)
    op.create_index('ix_auditlog_user_action', 'AuditLog', ['user_id', 'action'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_auditlog_user_action', table_name='AuditLog')
    op.drop_index('ix_auditlog_resource', table_name='AuditLog')
    op.drop_index('ix_auditlog_created_at', table_name='AuditLog')
    op.drop_index(op.f('ix_AuditLog_user_id'), table_name='AuditLog')
    op.drop_index(op.f('ix_AuditLog_resource_type'), table_name='AuditLog')
    op.drop_index(op.f('ix_AuditLog_id'), table_name='AuditLog')
    op.drop_index(op.f('ix_AuditLog_email'), table_name='AuditLog')
    op.drop_index(op.f('ix_AuditLog_action'), table_name='AuditLog')
    op.drop_table('AuditLog')
    op.drop_index('ix_activitylog_user_endpoint', table_name='ActivityLog')
    op.drop_index('ix_activitylog_status', table_name='ActivityLog')
    op.drop_index('ix_activitylog_created_at', table_name='ActivityLog')
    op.drop_index(op.f('ix_ActivityLog_user_id'), table_name='ActivityLog')
    op.drop_index(op.f('ix_ActivityLog_request_id'), table_name='ActivityLog')
    op.drop_index(op.f('ix_ActivityLog_id'), table_name='ActivityLog')
    op.drop_index(op.f('ix_ActivityLog_endpoint'), table_name='ActivityLog')
    op.drop_table('ActivityLog')
    # ### end Alembic commands ###
