"""empty message

Revision ID: 7c20b4fb6dcc
Revises: 
Create Date: 2025-03-11 18:23:42.857430

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils
import sqlmodel # added


# revision identifiers, used by Alembic.
revision = '7c20b4fb6dcc'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    op.execute("CREATE EXTENSION IF NOT EXISTS pg_trgm") 
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Media',
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('path', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_Media_id'), 'Media', ['id'], unique=False)
    op.create_table('Role',
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_Role_id'), 'Role', ['id'], unique=False)
    op.create_table('UserFollow',
    sa.Column('user_id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('target_user_id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('is_mutual', sa.Boolean(), server_default='0', nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_UserFollow_id'), 'UserFollow', ['id'], unique=False)
    op.create_table('ImageMedia',
    sa.Column('file_format', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('media_id', sqlmodel.sql.sqltypes.GUID(), nullable=True),
    sa.ForeignKeyConstraint(['media_id'], ['Media.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ImageMedia_id'), 'ImageMedia', ['id'], unique=False)
    op.create_table('User',
    sa.Column('first_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('last_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_superuser', sa.Boolean(), nullable=False),
    sa.Column('birthdate', sa.DateTime(timezone=True), nullable=True),
    sa.Column('role_id', sqlmodel.sql.sqltypes.GUID(), nullable=True),
    sa.Column('phone', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('gender', sa.Enum('female', 'male', 'other', name='igenderenum'), nullable=False),
    sa.Column('email_verified', sa.Boolean(), nullable=False),
    sa.Column('state', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('country', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('address', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('provider', sa.Enum('email', 'google', 'github', 'facebook', 'twitter', name='authprovider'), nullable=False),
    sa.Column('provider_user_id', sa.String(), nullable=True),
    sa.Column('id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('hashed_password', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('image_id', sqlmodel.sql.sqltypes.GUID(), nullable=True),
    sa.Column('follower_count', sa.BigInteger(), server_default='0', nullable=True),
    sa.Column('following_count', sa.BigInteger(), server_default='0', nullable=True),
    sa.ForeignKeyConstraint(['image_id'], ['ImageMedia.id'], ),
    sa.ForeignKeyConstraint(['role_id'], ['Role.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_User_email'), 'User', ['email'], unique=True)
    op.create_index(op.f('ix_User_hashed_password'), 'User', ['hashed_password'], unique=False)
    op.create_index(op.f('ix_User_id'), 'User', ['id'], unique=False)
    op.create_table('ExamDescription',
    sa.Column('id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('slug', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_by_id', sqlmodel.sql.sqltypes.GUID(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['User.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('slug')
    )
    op.create_index(op.f('ix_ExamDescription_id'), 'ExamDescription', ['id'], unique=False)
    op.create_table('ExamInstruction',
    sa.Column('id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('slug', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_by_id', sqlmodel.sql.sqltypes.GUID(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['User.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('slug')
    )
    op.create_index(op.f('ix_ExamInstruction_id'), 'ExamInstruction', ['id'], unique=False)
    op.create_table('ExamTitle',
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('slug', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_by_id', sqlmodel.sql.sqltypes.GUID(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['User.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('slug')
    )
    op.create_index(op.f('ix_ExamTitle_id'), 'ExamTitle', ['id'], unique=False)
    op.create_table('Faculty',
    sa.Column('id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('slug', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('image_id', sqlmodel.sql.sqltypes.GUID(), nullable=True),
    sa.Column('created_by_id', sqlmodel.sql.sqltypes.GUID(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['User.id'], ),
    sa.ForeignKeyConstraint(['image_id'], ['ImageMedia.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('slug')
    )
    op.create_index(op.f('ix_Faculty_id'), 'Faculty', ['id'], unique=False)
    op.create_table('Group',
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('created_by_id', sqlmodel.sql.sqltypes.GUID(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['User.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_Group_id'), 'Group', ['id'], unique=False)
    op.create_table('Institution',
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('institution_type', sa.Enum('UNIVERSITY', 'COLLEGE', 'TVET', 'OTHER', name='institutiontypes'), nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('phone_number', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('slug', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('image_id', sqlmodel.sql.sqltypes.GUID(), nullable=True),
    sa.Column('created_by_id', sqlmodel.sql.sqltypes.GUID(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['User.id'], ),
    sa.ForeignKeyConstraint(['image_id'], ['ImageMedia.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('slug')
    )
    op.create_index(op.f('ix_Institution_email'), 'Institution', ['email'], unique=True)
    op.create_index(op.f('ix_Institution_id'), 'Institution', ['id'], unique=False)
    op.create_table('Module',
    sa.Column('id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('slug', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('unit_code', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_by_id', sqlmodel.sql.sqltypes.GUID(), nullable=True),
    sa.Column('image_id', sqlmodel.sql.sqltypes.GUID(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['User.id'], ),
    sa.ForeignKeyConstraint(['image_id'], ['ImageMedia.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('slug'),
    sa.UniqueConstraint('unit_code')
    )
    op.create_index(op.f('ix_Module_id'), 'Module', ['id'], unique=False)
    op.create_table('Programme',
    sa.Column('name', sa.Enum('CERTIFICATE', 'DIPLOMA', 'UNDERGRADUATE', 'MASTERS', 'POSTGRADUATE_DIPLOMA', 'PHD_PROGRAMMES', 'ONLINE_MBA', 'OTHERS', name='programmetypes'), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('slug', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_by_id', sqlmodel.sql.sqltypes.GUID(), nullable=True),
    sa.Column('image_id', sqlmodel.sql.sqltypes.GUID(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['User.id'], ),
    sa.ForeignKeyConstraint(['image_id'], ['ImageMedia.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('slug')
    )
    op.create_index(op.f('ix_Programme_id'), 'Programme', ['id'], unique=False)
    op.create_table('QuestionSet',
    sa.Column('title', sa.Enum('QUESTION_ONE', 'QUESTION_TWO', 'QUESTION_THREE', 'QUESTION_FOUR', 'QUESTION_FIVE', 'QUESTION_SIX', 'QUESTION_SEVEN', 'QUESTION_EIGHT', 'QUESTION_NINE', 'QUESTION_TEN', name='questionsettitleenum'), nullable=True),
    sa.Column('id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('slug', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_by_id', sqlmodel.sql.sqltypes.GUID(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['User.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug'),
    sa.UniqueConstraint('title')
    )
    op.create_index(op.f('ix_QuestionSet_id'), 'QuestionSet', ['id'], unique=False)
    op.create_table('Team',
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('headquarters', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('created_by_id', sqlmodel.sql.sqltypes.GUID(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['User.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_Team_id'), 'Team', ['id'], unique=False)
    op.create_index(op.f('ix_Team_name'), 'Team', ['name'], unique=False)
    op.create_table('Campus',
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('slug', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('address', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('institution_id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('created_by_id', sqlmodel.sql.sqltypes.GUID(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['User.id'], ),
    sa.ForeignKeyConstraint(['institution_id'], ['Institution.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('address'),
    sa.UniqueConstraint('slug')
    )
    op.create_index(op.f('ix_Campus_id'), 'Campus', ['id'], unique=False)
    op.create_table('Course',
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('slug', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('course_acronym', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('programme_id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('created_by_id', sqlmodel.sql.sqltypes.GUID(), nullable=True),
    sa.Column('image_id', sqlmodel.sql.sqltypes.GUID(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['User.id'], ),
    sa.ForeignKeyConstraint(['image_id'], ['ImageMedia.id'], ),
    sa.ForeignKeyConstraint(['programme_id'], ['Programme.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('course_acronym'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('slug')
    )
    op.create_index(op.f('ix_Course_id'), 'Course', ['id'], unique=False)
    op.create_table('Department',
    sa.Column('id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('slug', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('image_id', sqlmodel.sql.sqltypes.GUID(), nullable=True),
    sa.Column('faculty_id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('created_by_id', sqlmodel.sql.sqltypes.GUID(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['User.id'], ),
    sa.ForeignKeyConstraint(['faculty_id'], ['Faculty.id'], ),
    sa.ForeignKeyConstraint(['image_id'], ['ImageMedia.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('slug')
    )
    op.create_index(op.f('ix_Department_id'), 'Department', ['id'], unique=False)
    op.create_table('Hero',
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('secret_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('team_id', sqlmodel.sql.sqltypes.GUID(), nullable=True),
    sa.Column('id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('created_by_id', sqlmodel.sql.sqltypes.GUID(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['User.id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['Team.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_Hero_age'), 'Hero', ['age'], unique=False)
    op.create_index(op.f('ix_Hero_id'), 'Hero', ['id'], unique=False)
    op.create_index(op.f('ix_Hero_name'), 'Hero', ['name'], unique=False)
    op.create_table('InstitutionFacultyLink',
    sa.Column('id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('institution_id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('faculty_id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.ForeignKeyConstraint(['faculty_id'], ['Faculty.id'], ),
    sa.ForeignKeyConstraint(['institution_id'], ['Institution.id'], ),
    sa.PrimaryKeyConstraint('id', 'institution_id', 'faculty_id')
    )
    op.create_index(op.f('ix_InstitutionFacultyLink_id'), 'InstitutionFacultyLink', ['id'], unique=False)
    op.create_table('LinkGroupUser',
    sa.Column('id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('group_id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('user_id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['Group.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['User.id'], ),
    sa.PrimaryKeyConstraint('id', 'group_id', 'user_id')
    )
    op.create_index(op.f('ix_LinkGroupUser_id'), 'LinkGroupUser', ['id'], unique=False)
    op.create_table('CourseModuleLink',
    sa.Column('id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('course_id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('module_id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['Course.id'], ),
    sa.ForeignKeyConstraint(['module_id'], ['Module.id'], ),
    sa.PrimaryKeyConstraint('id', 'course_id', 'module_id')
    )
    op.create_index(op.f('ix_CourseModuleLink_id'), 'CourseModuleLink', ['id'], unique=False)
    op.create_table('ExamPaper',
    sa.Column('year_of_exam', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('exam_duration', sa.Integer(), nullable=True),
    sa.Column('exam_date', sa.Date(), nullable=True),
    sa.Column('id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('created_by_id', sqlmodel.sql.sqltypes.GUID(), nullable=True),
    sa.Column('description_id', sqlmodel.sql.sqltypes.GUID(), nullable=True),
    sa.Column('title_id', sqlmodel.sql.sqltypes.GUID(), nullable=True),
    sa.Column('course_id', sqlmodel.sql.sqltypes.GUID(), nullable=True),
    sa.Column('institution_id', sqlmodel.sql.sqltypes.GUID(), nullable=True),
    sa.Column('hash_code', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['Course.id'], ),
    sa.ForeignKeyConstraint(['created_by_id'], ['User.id'], ),
    sa.ForeignKeyConstraint(['description_id'], ['ExamDescription.id'], ),
    sa.ForeignKeyConstraint(['institution_id'], ['Institution.id'], ),
    sa.ForeignKeyConstraint(['title_id'], ['ExamTitle.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('hash_code')
    )
    op.create_index(op.f('ix_ExamPaper_id'), 'ExamPaper', ['id'], unique=False)
    op.create_table('ProgrammeDepartmentLink',
    sa.Column('id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('programme_id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('department_id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.ForeignKeyConstraint(['department_id'], ['Department.id'], ),
    sa.ForeignKeyConstraint(['programme_id'], ['Programme.id'], ),
    sa.PrimaryKeyConstraint('id', 'programme_id', 'department_id')
    )
    op.create_index(op.f('ix_ProgrammeDepartmentLink_id'), 'ProgrammeDepartmentLink', ['id'], unique=False)
    op.create_table('ExamPaperQuestionLink',
    sa.Column('id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('question_set_id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('exam_id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.ForeignKeyConstraint(['exam_id'], ['ExamPaper.id'], ),
    sa.ForeignKeyConstraint(['question_set_id'], ['QuestionSet.id'], ),
    sa.PrimaryKeyConstraint('id', 'question_set_id', 'exam_id'),
    sa.UniqueConstraint('exam_id', 'question_set_id', name='_exam_paper_question_set_uc')
    )
    op.create_index(op.f('ix_ExamPaperQuestionLink_id'), 'ExamPaperQuestionLink', ['id'], unique=False)
    op.create_table('InstructionExamsLink',
    sa.Column('id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('instruction_id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('exam_id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.ForeignKeyConstraint(['exam_id'], ['ExamPaper.id'], ),
    sa.ForeignKeyConstraint(['instruction_id'], ['ExamInstruction.id'], ),
    sa.PrimaryKeyConstraint('id', 'instruction_id', 'exam_id')
    )
    op.create_index(op.f('ix_InstructionExamsLink_id'), 'InstructionExamsLink', ['id'], unique=False)
    op.create_table('MainQuestion',
    sa.Column('text', sa.TEXT(), nullable=False),
    sa.Column('marks', sa.Integer(), nullable=True),
    sa.Column('numbering_style', sa.Enum('ROMAN', 'ALPHA', name='numberingstyleenum', native_enum=False), nullable=False),
    sa.Column('question_number', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('slug', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('question_set_id', sqlmodel.sql.sqltypes.GUID(), nullable=True),
    sa.Column('exam_paper_id', sqlmodel.sql.sqltypes.GUID(), nullable=True),
    sa.Column('created_by_id', sqlmodel.sql.sqltypes.GUID(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['User.id'], ),
    sa.ForeignKeyConstraint(['exam_paper_id'], ['ExamPaper.id'], ),
    sa.ForeignKeyConstraint(['question_set_id'], ['QuestionSet.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('exam_paper_id', 'question_number', 'question_set_id', name='_questions_order_per_question_set_uc')
    )
    op.create_index(op.f('ix_MainQuestion_id'), 'MainQuestion', ['id'], unique=False)
    op.create_table('ModuleExamsLink',
    sa.Column('id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('module_id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('exam_id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.ForeignKeyConstraint(['exam_id'], ['ExamPaper.id'], ),
    sa.ForeignKeyConstraint(['module_id'], ['Module.id'], ),
    sa.PrimaryKeyConstraint('id', 'module_id', 'exam_id')
    )
    op.create_index(op.f('ix_ModuleExamsLink_id'), 'ModuleExamsLink', ['id'], unique=False)
    op.create_table('SubQuestion',
    sa.Column('id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('text', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('marks', sa.Integer(), nullable=True),
    sa.Column('main_question_id', sqlmodel.sql.sqltypes.GUID(), nullable=True),
    sa.Column('created_by_id', sqlmodel.sql.sqltypes.GUID(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['User.id'], ),
    sa.ForeignKeyConstraint(['main_question_id'], ['MainQuestion.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_SubQuestion_id'), 'SubQuestion', ['id'], unique=False)
    op.create_table('Answer',
    sa.Column('text', sa.TEXT(), nullable=False),
    sa.Column('id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('likes', sa.Integer(), nullable=False),
    sa.Column('dislikes', sa.Integer(), nullable=False),
    sa.Column('reviewed', sa.Boolean(), nullable=False),
    sa.Column('auto_answer', sa.Boolean(), nullable=False),
    sa.Column('created_by_id', sqlmodel.sql.sqltypes.GUID(), nullable=True),
    sa.Column('parent_id', sqlmodel.sql.sqltypes.GUID(), nullable=True),
    sa.Column('main_question_id', sqlmodel.sql.sqltypes.GUID(), nullable=True),
    sa.Column('sub_question_id', sqlmodel.sql.sqltypes.GUID(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['User.id'], ),
    sa.ForeignKeyConstraint(['main_question_id'], ['MainQuestion.id'], ),
    sa.ForeignKeyConstraint(['parent_id'], ['Answer.id'], ),
    sa.ForeignKeyConstraint(['sub_question_id'], ['SubQuestion.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_Answer_id'), 'Answer', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_Answer_id'), table_name='Answer')
    op.drop_table('Answer')
    op.drop_index(op.f('ix_SubQuestion_id'), table_name='SubQuestion')
    op.drop_table('SubQuestion')
    op.drop_index(op.f('ix_ModuleExamsLink_id'), table_name='ModuleExamsLink')
    op.drop_table('ModuleExamsLink')
    op.drop_index(op.f('ix_MainQuestion_id'), table_name='MainQuestion')
    op.drop_table('MainQuestion')
    op.drop_index(op.f('ix_InstructionExamsLink_id'), table_name='InstructionExamsLink')
    op.drop_table('InstructionExamsLink')
    op.drop_index(op.f('ix_ExamPaperQuestionLink_id'), table_name='ExamPaperQuestionLink')
    op.drop_table('ExamPaperQuestionLink')
    op.drop_index(op.f('ix_ProgrammeDepartmentLink_id'), table_name='ProgrammeDepartmentLink')
    op.drop_table('ProgrammeDepartmentLink')
    op.drop_index(op.f('ix_ExamPaper_id'), table_name='ExamPaper')
    op.drop_table('ExamPaper')
    op.drop_index(op.f('ix_CourseModuleLink_id'), table_name='CourseModuleLink')
    op.drop_table('CourseModuleLink')
    op.drop_index(op.f('ix_LinkGroupUser_id'), table_name='LinkGroupUser')
    op.drop_table('LinkGroupUser')
    op.drop_index(op.f('ix_InstitutionFacultyLink_id'), table_name='InstitutionFacultyLink')
    op.drop_table('InstitutionFacultyLink')
    op.drop_index(op.f('ix_Hero_name'), table_name='Hero')
    op.drop_index(op.f('ix_Hero_id'), table_name='Hero')
    op.drop_index(op.f('ix_Hero_age'), table_name='Hero')
    op.drop_table('Hero')
    op.drop_index(op.f('ix_Department_id'), table_name='Department')
    op.drop_table('Department')
    op.drop_index(op.f('ix_Course_id'), table_name='Course')
    op.drop_table('Course')
    op.drop_index(op.f('ix_Campus_id'), table_name='Campus')
    op.drop_table('Campus')
    op.drop_index(op.f('ix_Team_name'), table_name='Team')
    op.drop_index(op.f('ix_Team_id'), table_name='Team')
    op.drop_table('Team')
    op.drop_index(op.f('ix_QuestionSet_id'), table_name='QuestionSet')
    op.drop_table('QuestionSet')
    op.drop_index(op.f('ix_Programme_id'), table_name='Programme')
    op.drop_table('Programme')
    op.drop_index(op.f('ix_Module_id'), table_name='Module')
    op.drop_table('Module')
    op.drop_index(op.f('ix_Institution_id'), table_name='Institution')
    op.drop_index(op.f('ix_Institution_email'), table_name='Institution')
    op.drop_table('Institution')
    op.drop_index(op.f('ix_Group_id'), table_name='Group')
    op.drop_table('Group')
    op.drop_index(op.f('ix_Faculty_id'), table_name='Faculty')
    op.drop_table('Faculty')
    op.drop_index(op.f('ix_ExamTitle_id'), table_name='ExamTitle')
    op.drop_table('ExamTitle')
    op.drop_index(op.f('ix_ExamInstruction_id'), table_name='ExamInstruction')
    op.drop_table('ExamInstruction')
    op.drop_index(op.f('ix_ExamDescription_id'), table_name='ExamDescription')
    op.drop_table('ExamDescription')
    op.drop_index(op.f('ix_User_id'), table_name='User')
    op.drop_index(op.f('ix_User_hashed_password'), table_name='User')
    op.drop_index(op.f('ix_User_email'), table_name='User')
    op.drop_table('User')
    op.drop_index(op.f('ix_ImageMedia_id'), table_name='ImageMedia')
    op.drop_table('ImageMedia')
    op.drop_index(op.f('ix_UserFollow_id'), table_name='UserFollow')
    op.drop_table('UserFollow')
    op.drop_index(op.f('ix_Role_id'), table_name='Role')
    op.drop_table('Role')
    op.drop_index(op.f('ix_Media_id'), table_name='Media')
    op.drop_table('Media')
    # ### end Alembic commands ###
