"""add faculty relationship to course

Revision ID: 8b850100a3b5
Revises: 16b1a52b7e35
Create Date: 2025-10-07 08:42:59.396180

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils
import sqlmodel # added


# revision identifiers, used by Alembic.
revision = '8b850100a3b5'
down_revision = '16b1a52b7e35'
branch_labels = None
depends_on = None


def upgrade():
    op.execute("CREATE EXTENSION IF NOT EXISTS pg_trgm") 
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Course', sa.Column('faculty_id', sa.Uuid(), nullable=True))
    op.create_foreign_key(None, 'Course', 'Faculty', ['faculty_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'Course', type_='foreignkey')
    op.drop_column('Course', 'faculty_id')
    # ### end Alembic commands ###
