"""empty message

Revision ID: 52c8e675e21e
Revises: 470ad68a516e
Create Date: 2025-03-24 10:36:08.969773

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils
import sqlmodel # added


# revision identifiers, used by Alembic.
revision = '52c8e675e21e'
down_revision = '470ad68a516e'
branch_labels = None
depends_on = None


def upgrade():
    op.execute("CREATE EXTENSION IF NOT EXISTS pg_trgm") 
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('MainQuestion', 'exam_paper_id',
               existing_type=sa.UUID(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('MainQuestion', 'exam_paper_id',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###
