"""empty message

Revision ID: 37215c41382a
Revises: 630db79884b5
Create Date: 2025-04-12 08:36:46.753927

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils
import sqlmodel # added


# revision identifiers, used by Alembic.
revision = '37215c41382a'
down_revision = '630db79884b5'
branch_labels = None
depends_on = None


def upgrade():
    op.execute("CREATE EXTENSION IF NOT EXISTS pg_trgm") 
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_institution_created_at', table_name='Institution')
    op.drop_index('idx_institution_name', table_name='Institution')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_institution_name', 'Institution', ['name'], unique=False)
    op.create_index('idx_institution_created_at', 'Institution', ['created_at'], unique=False)
    # ### end Alembic commands ###
