"""unique_slug_constraint_and_question_updates

Revision ID: 2d33f2d3a351
Revises: 926b40094958
Create Date: 2025-12-28 08:42:54.529488

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils
import sqlmodel # added


# revision identifiers, used by Alembic.
revision = '2d33f2d3a351'
down_revision = '926b40094958'
branch_labels = None
depends_on = None


def upgrade():
    op.execute("CREATE EXTENSION IF NOT EXISTS pg_trgm") 
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'Question', ['slug'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'Question', type_='unique')
    # ### end Alembic commands ###
